### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#1]
So, how to get started best? 

@lislis would you want to start out with a basic scaffold for the page so we can all look at it? Or would you want to use some kind of mockup tool first? I guess it would be great if you gave some guidance :)

As for the contents, we'd want to outline the idea. Again, here's the gist with the original notes: https://gist.github.com/svenfuchs/a10e65117f84b61aca41

Who's good at writing?

I guess we have a bunch of separate "target groups" for this page:
1. Projects. Ask them to register somewhere, outline their project idea, possible goals, name a mentor etc.
2. Students. Ask them to register somewhere, so we have their name, location and contact data. Some info on what their skills and background is, what they're interested in most, what they expect to get out of the project etc.
3. Coaches. Same as with students, but we'd also like to know how much time they can put into this, if they can provide a desk at their workplace (or similar solution) and if their company would be up to allow some free time for supporting the student (in case they're employed).

Once we have this AND we've figured out how to do sponsorships we can later expand the page and add a section for companies.

**Comment by ellenkoenig** [comment]
I would be happy to help out with writing and structuring content.

**Comment by lucaspinto** [comment]
Who should actually submit the projects?
The student or the company who are looking for someone to mentor?

**Comment by svenfuchs** [comment]
@EllenKoenig feel free to just go ahead. use any format you feel most comfortable with. let's get started! :)

@lucaspinto the project maintainer :) e.g. @rkh might think that it'd be cool if the sinatra docs/website would get an overhaul for sinatra 2.0 then he might submit this as a project.

Project mentors on the one hand and coaches on the other hand can but don't need to be the same role. Project mentors need to know the project well, be able to set goals and make corrections based on that. Coaches can be people who are able to support students well, e.g. by offering a desk and some spare time, guide students through the ways of open source work, etc. They'll just offer support, motivation, help. Does that make sense?

**Comment by ghost** [comment]
I can help with the content too, also with the website coding if needed - not too hot at RoR yet but good knowledge of HTML/CSS, Javascript etc :)

**Comment by svenfuchs** [comment]
@jolenedunne \m/

we don't need to make this a rails app in order to get started. actually, we've had the idea to use GitHub pages for starters which uses jekyll: http://pages.github.com

**Comment by lucaspinto** [comment]
I like the idea of having two different roles mentor/coach. It does make sense to me.

**Comment by plexus** [comment]
Regarding the question of when to pay or what to consider as "succesfully
completed", I would vote for not having a hard goal or criteria.

Pay the participants enough to sustain themselves, and expect that they
actively and meaningfully engage with the project. Give the mentors/coaches
the power to veto if they really feel the participant has blatantly
neglected that.

My feeling is that since we're not necessarily aiming for implementing
features, like Google SoC, but rather community engagement/contribution in
whatever form, all you really need is a safety mechanism for cutting out
slackers/freeloaders.

**Comment by svenfuchs** [comment]
@arnebrasseur very much +1. would you mind writing up a paragraph on that which could be used as an entry on an faq or possibly the page itself? (obviously this would be still up for discussion, just like everything else, but let's just start collecting snippets)

**Comment by lislis** [comment]
@svenfuchs I created the necessary gh-pages branch, the site is alvailable via http://railsgirlsberlin.github.com/summer-of-code/ until an 'official' domain is set.
I think we should discuss mockups and stuff at the meetup. Then we will probably talk about the content and structure and so on anyway, cause it's important to the whole idea.
And than a separate issue for discussing the gh-page branch/ website should be enough.

**Comment by svenfuchs** [comment]
@lislis **fantastic**!

We'll definitely want to discuss things at the meetup, but I've got a feeling we should try an push things forward earlier than that. The meeting is still one week away and the site is just the first step in a long row of things to be sorted until "summer". (Not trying to build up any pressure, but I feel we should try and not loose time either unless necessary.)

What do you think? Could we try and put a basic version together (maybe using placeholder texts where we still need to fill things in) so we can have something to look at and work on the missing pieces at the meeting?

**Comment by nanoparsec** [comment]
If you want, I can buy a fitting domain and forward to the site. I just
need some name ideas :)

2013/3/27 Sven Fuchs notifications@github.com

**Comment by svenfuchs** [comment]
@NerdBabe thank you! i think this github subdomain is good enough for a good while, though. no need to spend money :)

**Comment by svenfuchs** [comment]
I've written up a few, initial words that maybe could be used for the first scaffold version:

https://gist.github.com/svenfuchs/2bdac2da44bb383962fa

@lislis wdyt?

everyone: feel free to add, replace, improve, ... :)

**Comment by nanoparsec** [comment]
I don't know if it`s clever to let students and sponsors participate to our
organizing googlegroup? Maybe we should have another group for them as we
have at rails girls berlin.
I can provide an email address like summer-of-code@railsgirlsberlin.de (or
from another domain. my provider has cheap .de domains to offer hehe.).

Best Ute

2013/3/27 Sven Fuchs notifications@github.com

**Comment by svenfuchs** [comment]
@NerdBabe good point, what was i thinking. well, i guess we could just hook up more wufoo forms for students and companies instead?

**Comment by nanoparsec** [comment]
for Applikation for Workshops we use Google forms. and i became a
big.friend of them.
i dont know woofoo yet :)

(walking and writing is difficult)
Am 27.03.2013 18:12 schrieb "Sven Fuchs" notifications@github.com:

**Comment by lislis** [comment]
@svenfuchs A very good start! I'll have some free time tomorrow to get some of the markup done.

**Comment by svenfuchs** [comment]
@lislis I just had the idea that we could just use one of those nice photos from a RailsGirls event as a background/eyecatcher for a blurb? a group of students working, a room full of people having fun, ... something like that? @phenriettak do you think that would be an appropriate thing to do?

**Comment by svenfuchs** [comment]
@NerdBabe Great! I've added another issue for the forms stuff: #2 :)

**Comment by phenriettak** [comment]
@svenfuchs  :) everything here sounds amazing :+1:

**Comment by svenfuchs** [comment]
some pics here: 

http://www.facebook.com/railsgirls/photos_stream/
http://www.flickr.com/photos/hone/sets/72157630499718690/
http://www.flickr.com/photos/hone/sets/72157630389505412/
http://www.flickr.com/photos/hone/sets/72157629923663006/
http://www.flickr.com/photos/hone/sets/72157629922495780/

**Comment by jmentz** [comment]
Yesterday did only one attendee show up in my project group. We talked about the Summer of Code and she is a designer, so we decided to create a mockup about how the summer of code website might look.

This is the result so far:
https://docs.google.com/file/d/0B2vUqCrhA1KtMGdyX1F1SkViQkU/edit?pli=1
a PSD file is availabe.

Katharina would also be very interested in taking part to continue learning Ruby and Rails. I added a new tab "interested attendees" to the Planning Google Doc and added her and Carolina.

**Comment by fannivuniconnu** [comment]
awesome!
Cheers guys.

2013/3/29 Johannes Mentz notifications@github.com

**Comment by svenfuchs** [comment]
@jmentz awesome, thanks for kicking things off!

Have you seen this https://gist.github.com/svenfuchs/2bdac2da44bb383962fa a few comments up? :)

**Comment by jmentz** [comment]
Oh, i must have overseen that.

I just converted the design to html and pushed it to a repo:
https://github.com/jmentz/Rails-Girls-Summer-Of-Code-Website

I used initializr.com, so we got responsiveness for free. jQuery / modernizr, Google Analytics etc are also out of the box available.

Here two screenshots in case someone does not want to use git to checkout the site locally:
https://docs.google.com/file/d/0B2vUqCrhA1KtRW5iUWVrRTNjSWs/edit?usp=sharing
https://docs.google.com/file/d/0B2vUqCrhA1KtOTFjOVBwWXFMWWs/edit?usp=sharing

Open Tasks are:
- forms to signup have to be created, links have to be adapted to them
- do we need an imprint?
- the header images have artifacts, because i made screenshots from a jpeg and compressed the new images again. I'll replace them with better ones exported from the original PSD.
- we could integrate facebook / twitter / google plus share buttons to help visitors to spread the word

**Comment by schultyy** [comment]
Hi
Are there already plan how to define tasks for the participants? If not, how about providing some sort of how to, that helps breaking tasks up and categorize in classes, for example beginner/advanced?

**Comment by nanoparsec** [comment]
Hey, I can design some logo, headers, etc for the site. I just need the dimensions :)

**Comment by nanoparsec** [comment]
I think we need an imprint. Maybe we can use the Rails Girls Berlin Imprint:
http://railsgirlsberlin.de/impressum/

+1 for social buttons.

I can set up a contact email address like summer-of-code@railsgirlsberlin.de

**Comment by jmentz** [comment]
Katharina made several new drafts for logos. I just attached them to my post here so that we can discuss about them.

![RG_summerofcode5](https://f.cloud.github.com/assets/334336/340068/b7e5ef24-9d45-11e2-8f08-a00ee864bd01.jpg)
![Logo_summer_of_code2](https://f.cloud.github.com/assets/334336/340069/b872109e-9d45-11e2-8814-94d60b07da46.jpg)
![RG_summerofcode6](https://f.cloud.github.com/assets/334336/340070/b8766cca-9d45-11e2-8466-797a95974f7e.jpg)

**Comment by fannivuniconnu** [comment]
Awesome. They do look great. Cheers Katharina.

I like the first one the most, with the Rails Girls font (is it the Rails Girls font?) and the Rainbow.

**Comment by phenriettak** [comment]
Woooow!!! Super nice! I like especially the simplicity of the "buttons" to choose from 

On Apr 4, 2013, at 7:36 PM, Johannes Mentz wrote:

Katharina made several new drafts for logos. I just attached them to my post here so that we can discuss about them.

**Comment by svenfuchs** [comment]
This is all pretty slick! :heart:  

I have a feeling we could make it bit more "bold", in a way, maybe add contrast and stuff, because what we're trying to achieve here is actually a bold thing :)

Does any of you @lislis, @jmentz, Katharina (?) have time tomorrow to meet at co.up and work on this a little? I'll be meeting with the rubymonsters and Matt in order to work on our app, but I'd also like to make some progress on this website before we meet on Sunday and discuss everything, if possible ...

C'mon! :)

**Comment by ellenkoenig** [comment]
Hey, I created a draft rewrite of the landing page on the wiki. https://github.com/RailsGirlsBerlin/summer-of-code/wiki/Website-landing-page----first-version-%28Projects-focus%29

Happy to see further edits or feedback comments. Especially to make the text even more engaging, bold and attention-grabbing.

**Comment by svenfuchs** [comment]
@carolinagc @lislis do you think one of these could be suitable for a big photo background at the top of the main page?

http://www.flickr.com/photos/hone/7517448204/in/set-72157630499718690
http://www.flickr.com/photos/hone/7517437204/in/set-72157630499718690
http://www.flickr.com/photos/hone/7517423204/in/set-72157630499718690
http://www.flickr.com/photos/hone/7517408602/in/set-72157630499718690

**Comment by carlad** [comment]
I like the first photo best...

**Comment by svenfuchs** [comment]
ZOMG right, we've got a photo pro on the team, how could i miss that! :D

@carladrago would you mind having a look at these sets and see if there's a pic that's even more suitable?

http://www.facebook.com/railsgirls/photos_stream/
http://www.flickr.com/photos/hone/sets/72157630499718690/
http://www.flickr.com/photos/hone/sets/72157630389505412/
http://www.flickr.com/photos/hone/sets/72157629923663006/
http://www.flickr.com/photos/hone/sets/72157629922495780/

I'm sure there are way more RailsGirls photos on flickr, but these are the ones that @phenriettak mentioned.

**Comment by carlad** [comment]
heh. an unambitious photo pro… ;-)

i still like that first one.
http://www.flickr.com/photos/hone/7517448204/in/set-72157630499718690

this one could work too
http://www.flickr.com/photos/hone/7517425306/in/set-72157630499718690/

**Comment by svenfuchs** [comment]
@lislis @somamo more design inspiration (along the lines of the berlin geekettes page that we've been looking at yesterday): http://elcocu.com

I also love the video! @txus ... could you pleeeaaase pull some strings there :)

(@somamo - sorry, I've mixed up your handle with @carolinagc's on the comment earlier ... soo bad with names!)

**Comment by somamo** [comment]
Thanks for the inspirations, pics and comments. I have done some screens for a new layout draft in a different style but still looking like railsgirls.com. You should watch them in full size. The navigation through the page could be realized like spotify.com does. You cklick on the arrow button and the next content part flips up. 

What do you think about the drafts? 

![RG_summerofcode9](https://f.cloud.github.com/assets/3679710/353972/ab0da514-a090-11e2-981c-25034ca796dc.jpg)
![RG_summerofcode10](https://f.cloud.github.com/assets/3679710/353973/ab0fa350-a090-11e2-9e98-f10b1ce6271a.jpg)

**Comment by carolinagc** [comment]
Yes!!! It looks great!! :-) ... for sure the photo that I like best is 
http://www.flickr.com/photos/hone/7517437204/in/set-72157630499718690

**Comment by svenfuchs** [comment]
@somamo I absolutely love the second one!

do you think it would be possible to make the background images "scroll over" as in http://elcocu.com or also http://mariusz.cc? I'm not sure what's the technical term for that effect. Ah, I see that https://www.spotify.com/de has a similar thing, too.

Also, maybe it'd be a good thing to plan for a "sticky" top menu bar like http://berlingeekettes.github.io/hackathon and http://elcocu.com do?

**Comment by ellenkoenig** [comment]
I love the second design as well :) I would suggest renaming the button for coaches, to show the word "coach" on the button rather than company. E.g. like this: "You are an experienced developer who wants to participate as a COACH".

**Comment by carolinagc** [comment]
I would also agree on having a "sticky" menu on top if its going to be a "just one" page website. although for me, it's not a format that I like too much, since I think its a bit confusing if by chance you scroll up or down and find different info from the one you were expecting. I think a page per piece of info its clearer and all of them can act as landing pages...but is just a suggestion

**Comment by lislis** [comment]
I'm also in for the second design.
@svenfuchs the effect is called parallax scrolling and I agree, that would be really cool. I would try to implement it w/ stellarJS https://github.com/markdalgleish/stellar.js
@carolinagc until we have all the texts for students and coaches etc. I think it's ok for us to work w/ a one-pager

**Comment by carolinagc** [comment]
@lislis totally agree, until we don't have all the texts is perfect to work on one-page option, I was just thinking in advance, because perhaps to have in mind certain ideas makes it easier to define a "scalable" design, so that at the end is less work ;)

**Comment by somamo** [comment]
I am glad you like the second screen draft. This kind of the navigation is suitable just for two or three content areas. I advise to use a secondary conventional navigation on top as carolinagc suggests. The first page is just an emotinal thing, to arouse interest and produce a wow effect. If a user desides to stay on the page and to get more information he clicks through the secondary navigation like here ===> http://support.spotify.com/de/learn-more/guides
If you already use spotify.com, you do not scroll the page every time, you just login and use a conventional navigation. 
The example elcocu.com shows that more then tree content areas on the first page are to much flashing.

**Comment by lislis** [comment]
I tried to implement the parallax effect w/ the second draft. Here you go http://railsgirlsberlin.github.io/summer-of-code/
I think it looks quite nice

**Comment by svenfuchs** [comment]
@lislis WOHA, AWESOME!!1! :heart:

**Comment by carlad** [comment]
yeah it looks great :-)

**Comment by rkh** [comment]
> I tried to implement the parallax effect w/ the second draft. Here you go http://railsgirlsberlin.github.io/summer-of-code/
> I think it looks quite nice

Looks pretty awesome. The first image is a bit low quality, I see artefacts when viewing the page on a higher resolution:

![Screen Shot 2013-04-09 at 6 02 01 PM](https://f.cloud.github.com/assets/30442/357809/dfee3692-a12e-11e2-9752-a5f6c0060936.png)

**Comment by rkh** [comment]
Maybe adding some effect (ie, b&w or reduced saturation with color overlay) would fix that.

**Comment by lislis** [comment]
@rkh your're right about the pictures. I'll try to find a good/ simple solution

**Comment by carolinagc** [comment]
Yep, looks great, but somehow I would add the "projects wanted" at the top, if not I think its a long scroll to get to the part we are more interested in highlighting

**Comment by svenfuchs** [comment]
@lislis @somamo @EllenKoenig soooorry, i forgot to send the directions to the travis office earlier!

So, it's at Prinzessinnenstrasse 20, Aufgang B

![20120620-travis-office](https://f.cloud.github.com/assets/2208/363499/61b0e1ee-a205-11e2-8cc7-da6565bb918d.png)

You can either take the stairs at Aufgang B. Or you find the elevator and use the door bell. Or you give me a call 0151-6511200 or tweet and we'll pick you up :)

**Comment by svenfuchs** [comment]
@lislis @somamo about the font: 

![image](https://f.cloud.github.com/assets/2208/367360/789ea422-a2a5-11e2-97cb-c340fc9df865.png)

Here's the free Expressway version that Karri mentioned: https://typekit.com/fonts/expressway, looks good to me

@jmentz have you been able to find that assets folder? :)

**Comment by jmentz** [comment]
@svenfuchs
Yes, its located at http://railsgirls.com/assets .
The Interstate font can be downloaded from
http://railsgirls.com/assets/fonts . I sent the link yesterday to @somamo.

On Thu, Apr 11, 2013 at 2:45 PM, Sven Fuchs notifications@github.comwrote:

> @lislis https://github.com/lislis @somamo https://github.com/somamoabout the font:
> 
> [image: image]https://f.cloud.github.com/assets/2208/367360/789ea422-a2a5-11e2-97cb-c340fc9df865.png
> 
> Here's the free Expressway version that Karri mentioned:
> https://typekit.com/fonts/expressway, looks good to me
> 
> @jmentz https://github.com/jmentz have you been able to find that
> assets folder? :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RailsGirlsBerlin/summer-of-code/issues/1#issuecomment-16232084
> .

## 

http://www.johannesmentz.de

**Comment by phenriettak** [comment]
There's a load of photos also in RG Facebook, which you can try, or then check terence's flickr straight (if you didn't already, I see the photos are from SF <3) 
http://www.flickr.com/photos/hone/ :) 

looks amazing! Sorry am not much of use :( :( Will try help in the company phase ;) 

H

On Apr 11, 2013, at 4:22 PM, Johannes Mentz wrote:

@svenfuchs 
Yes, its located at http://railsgirls.com/assets . 
The Interstate font can be downloaded from 
http://railsgirls.com/assets/fonts . I sent the link yesterday to @somamo. 

On Thu, Apr 11, 2013 at 2:45 PM, Sven Fuchs notifications@github.comwrote: 

> @lislis https://github.com/lislis @somamo https://github.com/somamoabout the font: 
> 
> [image: image]https://f.cloud.github.com/assets/2208/367360/789ea422-a2a5-11e2-97cb-c340fc9df865.png 
> 
> Here's the free Expressway version that Karri mentioned: 
> https://typekit.com/fonts/expressway, looks good to me 
> 
> @jmentz https://github.com/jmentz have you been able to find that 
> assets folder? :) 
> 
> — 
> Reply to this email directly or view it on GitHubhttps://github.com/RailsGirlsBerlin/summer-of-code/issues/1#issuecomment-16232084 
> . 

## 

http://www.johannesmentz.de

**Comment by svenfuchs** [comment]
I've asked @hone (Terence) for permission to use those photos: "of course" :)

Are we supposed to/do we want to try and contact all the people on the photos as well in order to ask for permission?

**Comment by phenriettak** [comment]
Nah, go ahead. It seems to be jessicaspacekat and schneems in most of them anyhow ;) 

On Apr 11, 2013, at 6:52 PM, Sven Fuchs wrote:

I've asked @hone (Terence) for permission to use those photos: "of course" :)

Are we supposed to/do we want to try and contact all the people on the photos as well in order to ask for permission?

**Comment by phenriettak** [comment]
Hey guys, just thinking that for the summer it would be great to have an irc chat or something open to everyone, so that the trainees could ask each other or anyone available on the site for help if it happens to be busy in the company.. :) (Would be useful for nubheads like myself at least) 

So here in Krakow Applicake is super interested and a lot of other companies too - for example one sponsor or RG KRK already set up their own summer internship program especially for alumni of RG !!! (Still secret so can't say the name ) :) :)

**Comment by PragTob** [comment]
Wow that's super cool stuff happening in Krakow :-)

I agree an IRC channel would be super helpful and cool. We could make an #rgsoc channel at freenode. I'd love that :-)

**Comment by rkh** [comment]
Registered.

**Comment by lucaspinto** [comment]
@carladrago good move
