### ISSUE TITLE
Touches on buttons

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#10]
@lislis everytime i look at the buttons i feel like there's something wrong with the box-shadow ... it feels like they're in a "pressed" state.

i'd either just remove this shadow, or move them to :hover, maybe.

Also, can we change the margin to `2em 1em 2em 0`?

**Comment by PragTob** [comment]
Agreed. I think that the non hovered version should be the default version and the now default version the hovered version :-)

**Comment by jmentz** [comment]
I just changed the margin as suggested. The buttons align now nicer with the text above.

I also changed the appearance of the buttons, as explained in http://inspectelement.com/tutorials/create-a-slick-css3-button-with-box-shadow-and-rgba . The buttons change now their look on :hover and :active.

**Comment by svenfuchs** [comment]
@jmentz it's much better now! 

sorry to be such a pain, but I think the states are still kinda mixed up :)

It looks right when you don't touch the button. But shouldn't the `:hover` and `:active` states be swapped? Cuz currently `:hover` seems "pressed", while `:active` is just flat? Or is that on purpose?

**Comment by jmentz** [comment]
:active should move the whole button about 3 pixels down (by setting position:relative; top:3px), like as if it was pushed down. Its best visible if you click the button and keep the mouse button pressed.

I just changed that value from 3 to 5px. Is that better?

If not, we could try to find a new effect for the :hover state and use the current :hover state as the :active state.

**Comment by svenfuchs** [comment]
Oh, I see. 

Hmmmm, I'd personally just make it "flat" (no shadow) on :hover and "pressed" (inner shadow top/left) when :active?

Or maybe that's just my old school way of looking at it ;)

**Comment by jmentz** [comment]
The github buttons and the ones I have in Ubuntu have in their default state an outer bottom/right shadow. If i hover them, their background gets a lightened / darkened. If i click them, they lose their bottom/right shadow and get an inset upper/left shadow. 

I like that they respond on hover, because they feel more clickable (at least for me). I'll try that tomorrow.

**Comment by lislis** [comment]
long time ago :)
