### ISSUE TITLE
FP: Teams in Sidebar

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code-2014#100]
I like the suggestion to list the teams w/ team name, link to their blog and their real names (as well as logos or image, see the original design for that).
There is already a ajax functionality to make a simple list (see sidebar blog) but I don't know who did it. Is it possible to spice it up? :)

**Comment by ngkhanhlinh** [comment]
Just wondering if anyone can help with this. I believe this would be a really nice feature on the front page. What do you think @anikalindtner? :)
