### ISSUE TITLE
Check new design for responsiveness

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code-2014#102]

**Comment by tjmcewan** [comment]
I've noticed this too.  The page looks quite weird in mobile Safari & mobile Chrome. :-/

**Comment by lislis** [comment]
I did some fixes, 264816efea79e6f959b49680f34ef97d8e9de998 and others. @tjmcewan would you mind checking again?

**Comment by tjmcewan** [comment]
@lislis looks good! :)  there's a big white gap where the video should be; not sure what could be done about that though...
