### ISSUE TITLE
Offtopic: Icon for Rails Girls Berlin-Github-Organization?

### ISSUE THREAD

**Issue by jmentz** [rails-girls-summer-of-code/summer-of-code-2014#11]
Could someone with admin privileges on the Rails Girls Berlin-Github-Organization maybe add a nice icon for the organization? 

Its currently just the default gray octocat.

Its basically just a gravatar image for the email adress which was used to set up the organization.

I would love to pick the colored heart which is also the logo on the Rails Girls Berlin website:
http://railsgirlsberlin.de/wp-content/uploads/2012/08/Rails-Girls-Berlin-4.png

**Comment by nanoparsec** [comment]
Done.

2013/4/21 Johannes Mentz notifications@github.com

**Comment by jmentz** [comment]
great, thanks!
