### ISSUE TITLE
Add a sponsors page

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code-2014#113]
A sponsors page!

So, the idea is that we have an extra page displaying all our lovely sponsors (with text?) and also reference this page from every blog post (by putting a link in the post layout). Is that right, @svenfuchs @anikalindtner ? Do we need something else?

Maybe @ngkhanhlinh is up for another great design ? :)

**Comment by svenfuchs** [comment]
yeah, basically similar to https://love.travis-ci.org/sponsors (disregard the blue box at the top)

**Comment by ngkhanhlinh** [comment]
Lovely idea! :-) 

Sure, I'll get started on the design this week. Would be even better if we can have all the text for each sponsor already, but meanwhile I can also use mock text. Do let me know if you have any suggestions, design-wise!

**Comment by anikalindtner** [comment]
hej @ngkhanhlinh , we actually DO have all the texts ready :) 
here in the tab sponsor description: https://docs.google.com/spreadsheet/ccc?key=0AkVJAfjB3hdvdDRxZWdOQmlISlRja0JrSk9ILTlSZ1E&usp=sharing

**Comment by ngkhanhlinh** [comment]
Thank you @anikalindtner! It seems that some of the sponsors (e.g. DaWanda, EngineYard) still haven't gotten any texts yet? But this is more than enough for the mock-up! :-)

**Comment by ngkhanhlinh** [comment]
At long last, here's the first draft for the sponsors page! :-)

It's only the first draft so let me know if there's anything you like to add or change. I'm thinking of adding more scribbles, but that may take the focus away from the content. What do you think? 

Also, the sponsors included here are the ones with descriptions provided. There are many others that still need description, but we can definitely add them later! 

![sponsor-ver-4](https://f.cloud.github.com/assets/4908043/1064190/b73b7410-1318-11e3-807c-0c9aaa0fe6ce.png)

**Comment by lislis** [comment]
@ngkhanhlinh super nice! This will look great :D 
I'm only wondering if the silver and bronze sponsors should be a little smaller than the platinum and gold sponsors? @anikalindtner @svenfuchs what do you think?

**Comment by svenfuchs** [comment]
Looks great! Ship it :)

**Comment by anikalindtner** [comment]
hej, i'd say, since the text will be shorter on the silver and bronze sponsors, we can visualize the different roles over that?

**Comment by lislis** [comment]
ok then I'll roll

**Comment by anikalindtner** [comment]
just let me know when you are ready - maybe don't link it first on the site and then we can edit the sponsor description per pull request before

**Comment by lislis** [comment]
Commit: 3690cdb5d8f79d2977e192f8f1875aad91322182
alright, you can reach the page here http://railsgirlssummerofcode.org/sponsors-thanks/
it's not linked anywhere yet. I added one example per category, the rest needs to be filled in.
Logo sizes can be varied through the wrapper classes of the logos.

Btw, I'll be in the office tomorrow around 18:20 ;)
