### ISSUE TITLE
fix sidebar in view-blog-post-mode

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#115]
now it looks like this:
![screen shot 2013-08-16 at 9 07 32 pm](https://f.cloud.github.com/assets/1711357/977612/48f71180-06a7-11e3-99cf-b573c18cc025.png)

and you can't scroll down. it's just cut off.. :( 

what to do @lislis?

**Comment by lislis** [comment]
acutally, it's this commit df82ae116cb20feb7a865aafc91926335adf33a1
