### ISSUE TITLE
check wavy-border.png 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#118]
![screen shot 2013-08-28 at 11 41 26 am](https://f.cloud.github.com/assets/1711357/1041065/486c0f48-0fc8-11e3-8ff2-19d92f6c63fb.png)

there are some stripes that smuggled themselves in i guess :D

**Comment by lislis** [comment]
Closed #ac499975d8de91b5ce3a597c0d745013ead3841b
