### ISSUE TITLE
write tweets

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#131]
-thank you tweets to all the wonderful people who helped out!

**Comment by FloorD** [comment]
Is there a list of who needs mentioning somewhere?

**Comment by anikalindtner** [comment]
hm... not really. i guess all the organizers and supervisors? and then we could have a #coach -day as well? hmm..

**Comment by FloorD** [comment]
Just not sure who we had already, did you document that somewhere?

**Comment by anikalindtner** [comment]
yupp, kinda. in clicking here on organizers etc...: http://teams.railsgirlssummerofcode.org/participants
and also alexandra and charlotte who helped with pr.
other then that, i don't know. i haven't been there from the beginning, so i won't know people who helped in the beginning. @svenfuchs might know though who to mention

**Comment by FloorD** [comment]
Hahaha I understand which people to thank, just don't want to 'double thank'. Anyways, I'll craft a few tweets, maybe you remember who we already thanked.

**Comment by anikalindtner** [comment]
ahhhh now i get it. sorry! slow thinking today :D
afaik we had none of them yet - except andy for #codingheroes. (the ones we thanked then, i took from the github repository) but we can mention him again, he's doing so much <3

you can log in with the RGSoC account to http://twuffer.com/home#/tweets/scheduled and check the tweets i wrote for the #codingheroes, so you know who we already mentioned..

**Comment by FloorD** [comment]
AHA! That works!
