### ISSUE TITLE
Add BubbleConf to conference tickets & scholarships in footer

### ISSUE THREAD

**Issue by FloorD** [rails-girls-summer-of-code/summer-of-code-2014#135]
![bubbleconf](https://f.cloud.github.com/assets/1087213/1182383/f6557582-2219-11e3-87fb-e8ddfd3c5e96.png)

THANKS <3

**Comment by anikalindtner** [comment]
@lislis could you do that still? put them in the footer? :)

**Comment by lislis** [comment]
done cd269ba12a7a827e465b63a33abb6f6cb27604a5 and close ;)
