### ISSUE TITLE
Rework the FAQ

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/summer-of-code-2014#145]
I started editing the FAQ
https://docs.google.com/document/d/1L6yVNKBtWj-J7z9hhRwdEuqVVAXe1sgG1JTc1raPWdk/edit?usp=sharing

Feedback welcome! Also, feel free to edit it directly.

**Comment by anikalindtner** [comment]
yay! thanks! 
i'm on it too. editing it a bit so that it's more clean and easy to use. will also devide it into different sections (e.g. student faq/ sponsor faq..)
