### ISSUE TITLE
Find Place for Sponsor Logos

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code-2014#147]
I would like to find a better solution to last year's 'all logos to the footer'. Ideas welcome :)

**Comment by svenfuchs** [comment]
@lislis from last year's experience I'd implement things the same way as we did for the old Travis CI love campaign. That would mean two changes mostly:
- have the logo cloud on the homepage only 
- add the sponsors page right from the beginning (progressively, add texts as soon as people send them) http://2013.railsgirlssummerofcode.org/sponsors-thanks

I guess that's not exactly what you've been thinking about and if you have good ideas for improving the logo cloud then shoot! :)

We need a solution that 
- is both very flexible (works right from the start when there are just very few sponsors, and continues still works later on with a huge number) and
- also gives sponsors the maximum amount of attention that we can provide

Many conferences have the same issue, and solve it in the same way ...

WDYT?

**Comment by lislis** [comment]
Not having the logos on every page is already very good. 
I also havent't thought of the sponsors page. Having that from the beginning is sufficient :)
