### ISSUE TITLE
Student application example draft

### ISSUE THREAD

**Issue by berlintam** [rails-girls-summer-of-code/summer-of-code-2014#150]
This is in reference to issue #144 

Let me know if I'm on the wrong track. It's still a WIP so comments are very much appreciated, as well as other examples/corrections.

---

The second annual Rails Girls Summer of Code is just around the corner, and as an applicant, you’re probably wondering what makes a good project, workspace, and coach/mentor, as well as how to go about finding these seemingly elusive necessities. To point you along your way, we’ve put together this little guide with successful examples from last year.
## Projects

RGSoC 2013 had teams from all around the world working on a number of exciting open source projects, with each team tackling their challenges in different ways. Here a few examples to whet your appetites:
- Team Species+ made a beautiful interactive app for displaying CITES protected animals in Poland using the Species+ API. (check it out here: http://species-app.herokuapp.com/)
- Team Spree contributed to Spree, an e-commerce application. They spent a large portion of their time learning Ruby on Rails, which enabled them to implement their small Spree feature towards the end of the summer.
- Team Punchgirls created on an open source job-board from scratch complete with twitter and github integration. (check it out here: http://jobs.punchgirls.com/)
- Team Inchworms worked on Sinatra, a library for serving HTTP from your Ruby program. It is simple, flexible, and mature. They worked alongside Sinatra maintainer Konstantin Haase. 
- Team Bundler worked on Bundler, one of the community’s most widely used gems. They made the documentation easier to access and to read. As the summer progressed, they also worked on small features and fixes as they popped up.
- Team Dysania worked on Discourse, a Rails forum software. They focused on extracting oneboxing, a feature of Discourse, into a gem.
- The New Rosies contributed to Conductor, a Web-UI for assisting in the development of Rails apps. They decided upon the project after seeing it on the 2013 Rails Girls Summer of Code project ideas page.
## Working Space

The ideal working space has the right number of desks, is close to your coach and/or mentor, has a strong internet connection, and is (in a perfect world) free to use. You’ll be happy to hear that this is not as hard to find as one might think, and many companies are excited about having learners within their midst. 
- When it came to somewhere to work, Team Species+ simply asked Hackerspace Kraków if they could use their space, and they said "ok". It's just that easy!
- Team Highway to Rails worked in the offices of Absolventa, where their two coaches and mentor were based. They were supplied with computers and sat within the development team of seven people who were always on hand to help. 
- The New Rosies worked at their University and met with their coaches and mentor on weekends.
- Soundcloud hosted two sponsored teams and one volunteer team in their offices last summer. The teams had desk space, daily access to coaches, and were surrounded by numerous excited programmers who were eager to hold workshops, host book-clubs, and chat over a free lunch.
- Team Punchgirls worked from home, and met up with their coaches a few days a week in cafes around Buenos Aires.
## Coaches

For a newbie to the world of programming, approaching someone you look up to and asking them to guide you through the next three months of your life can feel like a daunting task. But fear not! There are lots of programmers out there who love teaching and who will jump at the chance to change someone’s life.
- Team Species+ found their coach through WebMuses, a women empowered IT community in Poland, of which the team is a part. 
- Team Inchworms approached the coaches of their local Rails Girls project group.
- The New Rosies found their coaches and mentor via their local Ruby community.
- Team Spree put out a call on the Spree google group and were met with support, ideas, and enthusiasm from the community.
- Team Punchgirls found their coaches from the Rubysur community. They started with a mentor, who suggested a coach, who then brought another on board.
- A member of team Highway to Rails approached her co-workers and found coaches who were excited about teaching and passionate about helping women succeed in the field of web development.

We hope these examples take away some of the intimidation of getting started on your application process. Now get out there, approach some developers, and find a project you're excited out! We're excited to hear what you all come up with...

**Comment by anikalindtner** [comment]
hej @berlintam this is a great draft! 
i'd include other teams maybe to push the focus from berlin a bit. like including team species+ for example and some other teams. @svenfuchs also had some ideas, as far as i remember

**Comment by berlintam** [comment]
I agree, unfortunately I can't find anyone's blogs anymore so I was kinda going off memory... Is there a list of them anywhere? ( I know the 2013 site is gone-ish now...)

**Comment by sareg0** [comment]
I think this would actually make a really good blog post, coming from Tam. We could link the blog post to the Application Guide.

**Comment by berlintam** [comment]
@sareg0 I like that idea! It is quite bloggy.

**Comment by anikalindtner** [comment]
http://2013.railsgirlssummerofcode.org/ there you should find all the team blog posts and stuff...

sure thing! tam, do you think you can have it ready by tomorrow/friday?

**Comment by berlintam** [comment]
I can try, I'm heading to Stuttgart tonite though so I can't promise anything. I'm also waiting to hear back from Team Species. Soon though, defo! (that sounds really non-committal but it's not meant to be)

**Comment by sareg0** [comment]
If you need a hand Tam, lemme know, I can do it up for you, and publish, and you just get the text written?

**Comment by anikalindtner** [comment]
@berlintam @sareg0 sounds awesome! if you team up even better <3 say something if you need help, also @FloorD and I can give a hand. I'm mostly out tomorrow, because it's my birthday, but if you need more tome we can also publish it on the weekend or even monday if necessary.

**Comment by berlintam** [comment]
Ok, I added Team Species+ to the bottom of each of the 3 points. Does anyone think it needs more examples?

**Comment by anikalindtner** [comment]
cool!
maybe put them on top so that it's really no focus on berlin? 
also including team impress js might be nice, since it was in london. and maybe team punchgirls or new rosies? wdyt?

**Comment by berlintam** [comment]
sure, I'll reach out!

**Comment by anikalindtner** [comment]
<3

**Comment by anikalindtner** [comment]
hey @berlintam! any news on the status? did you hear back from the teams? otherwise i could give some infos about them collecting from what i know about them..

**Comment by berlintam** [comment]
sorry @anikalindtner , I was away in Stuttgart enjoying the tropical weather! I heard back from punchgirls and added them in. I haven't heard back from Magda. Can you send me contact info for the New Rosies?

**Comment by anikalindtner** [comment]
https://github.com/rails-girls-summer-of-code/summer-of-code-2013/blob/gh-pages/blog/_posts/2013-09-06-introducing-rgsoc-participant-magda.md

https://github.com/rails-girls-summer-of-code/summer-of-code-2013/blob/gh-pages/blog/_posts/2013-09-12-introducing-team-newrosies.md

might be useful? you could also have a look at the blog posts from the other teams and just pick one that already wrote down a lot of info in their blog post :)

**Comment by anikalindtner** [comment]
http://2013.teams.railsgirlssummerofcode.org/teams

overview of all the teams, just if you want to include somebody else..

**Comment by berlintam** [comment]
Ok, I'd say this is done. I'm hesitant to put in any more examples because then it'll just be an overwhelming list. None of the Berlin teams are beside each other, and I mentioned that they're from all around the world (which at this point is definitely true). I don't explicitly say which country they'll all from though, so this shouldn't really matter. Lemmie know! :cat: 

Oh, and I think the title of the blogpost should NOT be 'Student Application Example Draft' because that's not what this is anymore. I suppose it's more 'Ideas to get you started' or something more eloquent than that.

**Comment by sareg0** [comment]
Okay, great, where is the finished text? We could get it up on the blog today.
