### ISSUE TITLE
new setup with middleman

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code-2014#151]
Hey everyone! I looked a bit into [Middleman](http://middlemanapp.com/) as alternative site generator to Jekyll.
I put a setup together that uses a blogging plugin similar to Jekyll but as far as I see with more extras like tags. It can compile scss and markdown with live reload, so no need for guard or something. That also means I can put compass and susy grids in it ;)
And the best thing is there is a deploy plugin that creates a build and pushes only that build to the gh-pages branch of the remote repo :D 
Take a look at it here: https://github.com/lislis/middlemanghpages
I would very much like to use this one. Question is how change it on this repo? I could start styling and setting up all pages that are already prepared from the other issues.
What do you think?

**Comment by anikalindtner** [comment]
if it makes things easier, I'm all up for it and TAGS! i'd love tags!
so thumbs up from me!

**Comment by anikalindtner** [comment]
closed for now
