### ISSUE TITLE
Info for future coaches

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/summer-of-code-2014#154]
I wanna build a page/guide on what coaching/mentoring/helpdesking involves. Past experiences are very much appreciated. 

cc @lucaspinto @pxlpnk @carpodaster @svenfuchs @plexus what did or do you do when coaching/mentoring? what were the questions/things to deal with? how much time did you spend on it? what were your personal gainings? …

cc @carlad @queenfrankie @berlintam @ninabreznik  what were good experiences you had? what is stuff that should be avoided? …

**Comment by svenfuchs** [comment]
Here's a list of last years coaches btw http://2013.teams.railsgirlssummerofcode.org/users?sort=&direction=&role=coach

**Comment by carlad** [comment]
Advice to coaches from a student: Avoid over explaining. Assume no knowledge. Keep it as high level as possible. Draw pictures to helpmake the abstract more concrete. Be prepared to repeat yourself often. Always try to understand what the student is seeing. Don't worry if you don't make sense at first, just keep trying. Look forward to the buzz you will feel when your students understand (finally!). Know that they will love you forever for your patience and generosity.

**Comment by svenfuchs** [comment]
Someone help me rephrase this in a friendly way:

> Be patient and tolerant towards technologies and solutions. Whether or not you "hate" RSpec or TestUnit, ERB or Haml, or whatever text editor you prefer does not matter to students at all. They are in a learning position and whatever gets them started, curious and eager to learn is _good_, no matter your personal preferences. Keep in mind that your preferences, just like "common knowledge of the community" is a result of a long, long, long learning process which you, and the community have went through. You want people to get started, and interested

**Comment by anikalindtner** [comment]
@katrin-k: @carpodaster wanted to work on a guide for coaches. you two should join your efforts! :)

**Comment by anikalindtner** [comment]
@svenfuchs maybe something like this? (I found your version wasn't too unfriendly alreads so I only made a few changes)

> Coaches are first of all patient, tolerant and open people! This goes for everything but also for technologies and solutions you might not chose for yourself. Whether or not you don't like RSpec or TestUnit, ERB or Haml, or whatever text editor you prefer does not matter to students at all. They are in a learning position and whatever gets them started, curious and eager to learn is a perfect tool - no matter your personal preferences. Keep in mind that your preferences, just like "common knowledge of the community" is a result of a long, long, long learning process which you, and the community have went through. Give your students the same time and chance to discover and pick their favorites over time. Our goal is to get people started, learning and stay exited about coding!

**Comment by sareg0** [comment]
Sounds great @anikalindtner. I just have one or two grammar edits

"...long, long, long learning process which you, and the community have gone through. Give your students the same chance to discover and pick their favorites over time. Our goal is to get people started, learning and staying excited about coding!"

It was just those last two sentences that needed an edit.
x

**Comment by katrin-k** [comment]
sweet! cheers to all of you :). 
@carpodaster let's make this a pretty one

**Comment by svenfuchs** [comment]
I'd just remove this one:

> Give your students the same chance to discover and pick their favorites over time. 

Other than that: great! :)

**Comment by sareg0** [comment]
Okay, well I am happy to build a coach guide. Shall we have a seperate page in the navigation? Where would you like the page positioned.

**Comment by katrin-k** [comment]
+1 for separate page and separate nav. have it titled "coaches" and put besides students. 
Will add a first draft in here in a sec.

**Comment by katrin-k** [comment]
So. Here's the first draft. 

## Coach Guide

You heard about Rails Girls and want to be a coach? Here you’ll find all you need to know what coaching actually means.

### What it takes to be a coach

First of all, Coaches are patient, tolerant and open people! 
This goes for everything, but also for technologies and solutions you might not chose for yourself. Whether or not you like RSpec or TestUnit, ERB or Haml, or whatever text editor you prefer does not matter to students at all. They are in a learning position and whatever gets them started, curious and eager to learn is a perfect tool – no matter your personal preferences. 
Keep in mind that your preferences – just like "common knowledge of the community" – is a result of a long, long learning process which you, and the community have gone through. Give your students the same chance to discover. 
Our goal is to get people started, learning and staying excited about coding!

### What exactly is part of coaching?

#### During the application process

Advise on setting up the project plan (here’s what we expect and previous examples…)
--> Students don’t need grasp for the stars, but rather for the apples on the tree. So they can climb up the tree, instead of having to build a space elevator. Ask your students what they already know and what _exactly_ they want to learn. In short, figure out if they have an idea how to realize their idea and what’s part of the way. 

#### During the Summer of Code

Pair programming with a twist
[FURTHER EXPLANATION]

### How much time does it take?

During application (till end of April), a few hours a week. 
During the Summer (July to Sept), 1-2 hrs/day personal time plus chat/mail 
--> preferrably shared with a few other coaches (from a student’s perspective: they will continually run into stuff they need help with. Hence something like one day a week won’t be enough)
--> ask your company to become a coaching sponsor and your coworkers to join

### Good things to know

#### Teaching is learning.

Good learning means taking little steps and repeating them. As a coach, avoid over-explaining in great length. Explain one aspect, hold your breath and see, how your students understood what you said. Be prepared to explain again. 

#### Make it practical.

Let your students do the coding. That also counts for solving problems that are kinda beside the recent project goal. Remember, the Summer of Code is about learning all the aspects of coding.

#### Make it visual.

Pen & paper can be great tools to show how the code is working; e.g. the steps of how a variable from a views .erb is showing up in the HTML file in the browser.

#### Don’t worry.

There will be moments when your students won’t make sense out of what you say. You might feel you’re at your wits end, too. No worries. No one expects you to have all the answers. Just keep trying! We promise you one thing: You can look forward to the buzz you will feel when your students understand (finally!). Know that they will love you forever for your patience and generosity.

#### The community’s just a click away.

At RGSoC we have a network of mentors and people behind the helpdesk. Feel free to approach us whenever you reach a dead end. Also, ask your coworkers, ask the community and above all, don’t shy away from telling your students.

[CLOSING LINE WITH CONTACT]

**Comment by katrin-k** [comment]
For changes/addings, please hop over to the gist: https://gist.github.com/katrin-k/9490742

**Comment by carlad** [comment]
Love how you've expanded on my notes. Great work :-))

**Comment by carpodaster** [comment]
Poor man's diff view: https://gist.github.com/carpodaster/9495561/revisions

---

Elaboration on the project plan help:

#### During the application process

Advise on setting up the project plan: the plan should take a learning curve into account. While it can be difficult to estimate the initial skill-level and the -progression, you are likely to anticipate potential pitfalls and should communicate them accordingly. Help with some "stretch goals": the project plan may be laid out defensively, timewise, to allow for some yet unknown challenges. In the event that an unforeseen obstacle delays the teams' progression, it's rewarding and encouraging to still have the sense of a completed project and it's even more fulfilling if your team has indeed exceeded the actual plan by tackling additional optional features.

^- could do with a polish

---

New paragraph for »Good things to know« :

#### Take detours

Satisfy the curiosity of your students. The work on their project will spawn all of sorts of questions that are not directly related to their roadmap. Programming is a vast field – take your students on a tangent occasionally and explore how a web request is made, how a computer works or what all the different software licences are about.

**Comment by katrin-k** [comment]
updated the guide and sent it to our hopefully future coach Kinsey for feedback. As soon as her's is in, the Guide can go online.

**Comment by anikalindtner** [comment]
yay! sounds awesome! great work :yellow_heart:
