### ISSUE TITLE
Write Alumni Email

### ISSUE THREAD

**Issue by sareg0** [rails-girls-summer-of-code/summer-of-code-2014#155]
This is just a quick email to 2013 Alumni to ask for their support on RGSoC 2014. 

Formatting to be completed in Mailchimp, after the mailing list is put together from the Teams App.
## 

EMAIL SUBJECT: RGSoC Needs You in 2014!
TITLE: Summer of Code; Guide the Next Batch.

Hi There RGSoC Alumni!

We hope you have been keeping busy, making the most of all the skills you gained from your projects in 2013, and generally making the world a better place!

RGSoC for 2014 is now upon us, and we wanted to call on you to pass on your knowledge to the next batch of participants by coaching, mentoring and/or supervising a team during the Summer.

Remember those awesome people who answered your questions, and helped you with your projects last year? We want you to be one of them this year!

Please let us know if you would like to help, and in what capacity, by replying to this email.

Much love,
Your RGSoC Team
## 

If we have a form that we can direct them to, then we can just link it in, otherwise, just a quick and dirty text to get us started. 

We need to export the list of Teams from the Teams App in able to make a new mailing list in Mail Chimp.

xo
Sara

**Comment by sareg0** [comment]
@anikalindtner have we sent the email yet?

**Comment by anikalindtner** [comment]
oh! eheemmmmm... no

**Comment by anikalindtner** [comment]
i'll do it tonight

**Comment by sareg0** [comment]
it's cool, just checking up on old stuff ;)

**Comment by anikalindtner** [comment]
done! yeah! i propose you are now the head checker for EVERYTHING :D this worked great hehe ;)
