### ISSUE TITLE
put together /projects and application guide

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#156]
http://railsgirlssummerofcode.org/projects/

still has infos that seem the same as in the application guide. maybe we can put it together and delete the projects site?

**Comment by anikalindtner** [comment]
@sareg0 maybe something for you?

**Comment by sareg0** [comment]
Sure on it now.

**Comment by sareg0** [comment]
Okay, we will put the 'projects' page into retirement, as I have integrate the text into the application guide, and the other bits and pieces left over saved for the mentor guide. We will direct the FAQ question containing 'projects' with that link to the Application Guide#projectplan

The adjusted text for the application guide will be changed to the below

## 

## A project plan

A project can include anything that helps open source like: Bug fixing, implementing small features, documentation, design, etc. Anything that will allow a student to both apply her experience and grow with the challenge. The learning target, and goal, of the project is to turn yourself, as a Ruby newcomer, into a core contributor to your selected open source project. The ideal project should be:

considered a valuable, significant contribution to Open Source
is simple enough that a beginner will be able to complete it in a time frame of three months or less
Projects should have an end goal, as well as several subordinate goals and milestones, that participants can use to track their progress against.

Please meet with your coach and pair to discuss what project you are looking to undertake. Meeting with your coach is a great way to understand if your goals are realistic, and what your project plan will look like.

Together with you and your pair, coaches should be able to:
- talk to you both about your level of your expertise,
- make recommendations about open source projects that you could contribute to,
  help you create as detailed a project plan as possible for your 3 month SoC project.
  Projects will be assigned a mentor, who will act as an expert to consult on the project, and provide feedback and directions

If you are interested in more than one project, you can lodge an application for every project you want to work on, but each application must be unique to that project.

Don’t know where to start? Here’s a list of potential Projects to inspire you!
(https://github.com/rails-girls-summer-of-code/summer-of-code/wiki/Project-ideas)

**Comment by anikalindtner** [comment]
coolio!!

**Comment by svenfuchs** [comment]
> Projects will be assigned a mentor, who will act as an expert to consult on the project, and provide feedback and directions

Hmmm, that somewhat sounds as if the mentor was assigned to the project from outside. It's more like: Every project needs a mentor, i.e. an expert who gives general directions. Most of the time that expert will just be the maintainer of the open source project, or someone from their team. E.g. Konstantin Haase acted as the mentor for the Sinatra work that Carla and Anja were doing. Someone from the Rails core team acted as the mentor for the team that worked on the Rails tool.

Also, maybe take that sentence out of the bullet point?

Like

> Projects will have a mentor who will act as an expert to consult on the project, and give general directions and feedback. Mentors are intimately knowledgeable about the project, while coaches are working closely with you and your pair.

??

**Comment by sareg0** [comment]
Okay, that was a bit unclear from the outset. How do they find a mentor is the question that I would like to answer for them also. 

"Projects will have a mentor who will act as an expert to consult on the project, and give general directions and feedback. Mentors are intimately knowledgeable about the open source project you intend to work on, while coaches are working closely with you and your pair. You can find a mentor by ... "

**Comment by svenfuchs** [comment]
It's mostly all a process of talking to each other. Students might meet coaches at Rails Girls or other local events, know them from work, friends, ... or find them via Twitter. They might discuss their ideas. Coaches might suggest projects they know. They'd contact their maintainers and someone volunteers as a mentor.

Or it might work the other way around: Someone suggests their project as a potential RGSoC project. Then a team picks that idea up.

I reckon all of this is pretty unclear so far. 

There's also this idea to help with this process via our app: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/63

**Comment by sareg0** [comment]
Aha... Yes, a little tricky. Okay. Well
I will put this text in then:

## A project plan

A project can include anything that helps open source like bug fixing, implementing small features, improving documentation, design, etc. The project will allow a student to both apply her current experience and grow with the challenge. The learning target, and goal, of the project is to turn yourself, as a Ruby newcomer, into a core contributor to your selected open source project. The ideal project should be:
- considered a valuable, significant contribution to Open Source
- is simple enough that a beginner will be able to complete it in a time frame of three months or less

Projects should have an end goal, as well as several subordinate goals and milestones, that participants can use to track their progress against.

Please meet with your coach and pair to discuss what project you are looking to undertake. Meeting with your coach is a great way to understand if your goals are realistic, and what your project plan will look like.

Together with you and your pair, coaches should be able to:
- talk to you both about your level of your expertise,
- make recommendations about open source projects that you could contribute to, help you create as detailed a project plan as possible for your 3 month SoC project. 

If you are interested in more than one project, you can lodge an application for every project you want to work on, but each application must be unique to that project.

You should find a mentor who can act as an expert to consult on the project, and give general directions and feedback. Mentors are intimately knowledgeable about the open source project you intend to work on, while coaches are working closely with you and your pair. You can find a project mentor through your coach, or through the community, by contacting project maintainers directly. Mentors may even put forward ideas for teams to work on. If you have trouble finding a mentor, write as an email, and we'll see if we can help.

Don’t know where to start? Here’s a list of potential Projects to inspire you!
(https://github.com/rails-girls-summer-of-code/summer-of-code/wiki/Project-ideas)

## 

When the app is up, we can then link that up. But I didn't want to mention it, before it was ready :)

**Comment by berlintam** [comment]
maybe we can link to this in my blogpost ( #150 ) ? The two seem quite related.

**Comment by sareg0** [comment]
@berlintam yes, this is the application guide, so just link http://railsgirlssummerofcode.org/application-guide/ to your article. I will update that text now, I just wanted to make sure no one had any comments on it.

**Comment by sareg0** [comment]
Okay, so I have now updated the application guide to have this text as well as a link to the blog post from Tam... I shall now close this, but just reopen if it needs to be readdressed somehow. 
xo
