### ISSUE TITLE
Draft for a sponsors blog posts

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#157]
I don't have time to prepare a proper pull request right now, but I'd like to add this for @sareg0 for context.

Also, this is just a draft. Any and all feedback and improvements welcome! We're planning to publish this rather soon.

---

Last year's Rails Girls Summer of Code was a raging success: over 30 students
worked on Open Source projects over the summer, most of them fulltime and
sponsored by the community and our company sponsors.

Preparations for this year's installment have been kicked off and now we are
reaching out to companies, asking for their support.

This year we have three options for companies to join the program and support
a great cause.

We are looking for:
1. Sponsors: Offering the same packages as last year, giving you the
   opportunity to drive attention to your company and gain great exposure to the
   community.
2. Coaching companies: Support us by giving one or more developers the opportunity
   to host and coach a students team onsite.
3. Supporting organizer: This program has grown big, and so has the amount of
   work to be donw. We are looking for another company to join us and pay a
   supporting organizer part- or fulltime.

If you are interested in these please get in touch: [email?]

Some more details:
### 1. Sponsors

We will officially open our campaign on [date]. But since a lot of attention
goes out to the earliest subscribers we'd also like to give you the opportunity
to subscribe earlier. Sponsors will be ordered by package size and subscription
date, so early subscribers will go up.

Sponsors receive most attention through their company logos which will be
linked on our homepage. A dedicated sponsors page also lists all of our sponsor
logos alongside with a text that you are free to choose.

Other perks include: your swag in packages which are sent out to our student
teams, your logo on student's slides at conference talks, mentions in our press
kit and newsletters, blog posts dedicated to sponsors, lots of tweet love from
the community ... and Konstantin Haase wearing your tshirt at a conference and
mentioning you as a sponsor.

If you are interested in getting on board as a sponsor early, then please get
in touch: [email?]
### 2. Coaching companies

Some of last year's most successful students teams have been supported greatly
by local companies.

E.g. Soundcloud has not only been on board as a sponsor. The have also hosted
one students team at their Berlin developer's office. 

Developers were allowed to spend a certain amount of time on coaching these
students. By pooling a few coaches, giving students the opportunity to present
their work during company meetups and everyone meeting during lunch breaks they
have set up a fantastic support environment for this team. Other companies
provided similar setups with great success, too.

Often times companies have some sort of policy to allow developers to work on
Open Source or other projects during work time. If you do, ask your team if
they'd be interested in coaching a team of two students onsite.

There's one catch to this option: Students can't be picked upfront, but their
applications will be rated based on criteria, and the best ranking applications
will be selected.

You can greatly improve your team's chances to win a sponsored seat by helping
them prepare an outstanding application.

If you are interested in getting on board as a coaching company, then please 
get in touch: [email?] 
### 3. Supporting organizer

A good amount of work on organizing Rails Girls Summer of Code is done by
volunteers, and Travis CI supports Rails Girls Summer of Code by paying Anika
to work on this through Travis Foundation. 

Yet, since the amount of work is huge, and so we are looking for another
company to join us and pay an organizer's position part- or fulltime.

If you are interested in this, then please get in touch: [email?]

**Comment by sareg0** [comment]
Hey, I muss have commented in my changes elsewhere, as I can't find them anymore. Oh well

Lucky I edited the draft in drive.

## 

Rails Girls Summer of Code 2013 was a resounding success!

We had over 30 students working on Open Source projects over the summer, most on a full-time basis, sponsored by the community and our company sponsors. A significant amount of those students went on to present at conferences, and meetups, as well as moved onto their own coding projects!

Preparations for this year's instalment of SoC have begun, and we’re looking for companies to support this incredible program in 2014.

This year we have three options for companies to join and support the program; as Sponsors, Coaching companies and/or in financially supporting organizers.

## 1. Sponsors

While our fundraising campaign will officially begin on [date], sponsors who sign up early will get a significant amount of exposure, and publicity.

Sponsors are listed on the site not only according to the size of their donation, but also their sign up date. Our sponsorship packages will remain the same as they were in 2013, giving you the opportunity to choose your desired package early! Take a look at last year's packages [here].

Sponsor logos will be listed and linked via the Rails Girls Summer of Code homepage and on the dedicated 'Sponsors' page, with a blurb text that you are free to choose.

Other perks of sponsorship include: getting your swag in goody bags which are sent out to our student teams, your logo on students’ slides at conference talks, mentions in our press kit and newsletters, blog posts dedicated to sponsors, lots of tweet love from the community ... and Konstantin Haase wearing your T-shirt and mentioning you as a sponsor at a conference.

Want to be one of our early-bird sponsors? Get in touch with us: [email?]

## 2. Coaching companies

Some of last year's most successful student teams have been supported greatly by local ‘coaching companies’, who have given them a place to work in their offices and a pool of coaches to help them. We are looking to formalize this support into an option for interested companies this year.

A great examples from 2013 is SoundCloud, who sponsored SoC, and provided coaching resource for one student team at their Berlin developer office. 

Their developers were put into a coaching pool and alloted a certain amount of time to coach the students. Students presented their work during company meetings, and met with other staff members during lunch breaks. There were a number of other companies who provided similar setups with great success, too.

Some companies have policy in place to allow developers to work on Open Source, or other beneficial projects, during business hours. If you do, ask your team if they'd be interested in coaching a team of two students onsite.

There's one condition to this option: Students CANNOT be picked upfront. 

Student applications will be rated based on the set criteria, and the best ranked applications will be selected. However, you can greatly improve your team's chances of winning a sponsored seat by helping them prepare an outstanding application.

If you have the ability to be a 'Coaching Company' we'd love to hear from you: [email?]

## 3. Supporting organizers

A mammoth amount of work  goes into organizing Rails Girls Summer of Code, and a vast majority of it is done by volunteers. With the program set to grow in 2014, we would like to provide at least one paid position for an SoC Orga Team Member to dedicate themselves to Summer of Code organizational activities. 

A great example of financially supporting organizers is Travis CI, which supports Rails Girls Summer of Code by paying Anika Lindtner to work on the program, through the Travis Foundation.

The sponsored organizer will have displayed a track record of reliability and honesty, and will be vetted to ensure they will make terrific use of a paid position.

If you are interested in this new initiative, then please get in touch: [email?]

**Comment by svenfuchs** [comment]
@sareg0 amazing, you're just pumping out terrific drafts.

Do you want to go ahead and turn this into a pull request for an actual blog post? 

We'd just need to decide on a title for that, and tbh I don't have any good ideas so far.

"Rails Girls Summer of Code calling companies for support"

???

**Comment by svenfuchs** [comment]
Or maybe "Sponsors, coaching companies and supporting organizers"

**Comment by svenfuchs** [comment]
@sareg0 I've turned this into a pull request here: #161 ... so I think we can head over there, and close this one.
