### ISSUE TITLE
Coaching companies page

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#158]
Hey @sareg0 

As discussed earlier. This is the blog post that we want to publish for potential sponsors, coaching companies etc: #157 

For that it'd be fantastic if we already had a "Coaching Companies" page on our website, too, that we can link to and that adds extra detail.

It also would be very cool to include some photos (from soundcloud?) and links to actual company blog posts, our own blog posts from those teams etc. so that companies could _see_ what kind of attention they could expect out of this. @anikalindtner, hey, ping :)

Here are a few notes that I've quickly taken on the train, some of it is just copied from the blog post draft since I then had no more time to work on it:

```
# Coaching companies

Coaching companies host a students team and provide a support environment to
them by:

* assigning one or more developers with the task to coach the team
* provide work space and a desk
* include them to company events such as meetups, presentations etc

Some of the most successful teams last year were supported by coaching companies
such as Soundcloud, Travis CI and Absolventa.

These companies have proviced amazing support environments to their teams
and integrated


Developers were allowed to spend a certain amount of time on coaching these
students. By pooling a few coaches, giving students the opportunity to present
their work during company meetups and everyone meeting during lunch breaks they
have set up a fantastic support environment for this team. Other companies
provided similar setups with great success, too.

Often times companies have some sort of policy to allow developers to work on
Open Source or other projects during work time. If you do, ask your team if
they'd be interested in coaching a team of two students onsite.

There's one catch to this option: Students can't be picked upfront, but their
applications will be rated based on criteria, and the best ranking applications
will be selected.

You can greatly improve your team's chances to win a sponsored seat by helping
them prepare an outstanding application.

If you are interested in getting on board as a coaching company, then please
get in touch: [email?]


```

**Comment by sareg0** [comment]
That's a good idea, so that case studies such as SoundCloud can have a nice feature with photos.

**Comment by sareg0** [comment]
Okay, so I added my updated text for the blog post to #157, so @anikalindtner and  I can develop a text for this page; images, case studies, value proposition usw.

**Comment by anikalindtner** [comment]
ok, i'm gonna find the links to soundcloud blog posts and pictures etc.

**Comment by anikalindtner** [comment]
http://2013.railsgirlssummerofcode.org/blog/meet-team-rails-grrls/
http://2013.railsgirlssummerofcode.org/blog/friday/
http://blog.soundcloud.com/2013/07/19/rails-girls-summer-of-code-welcoming-nicole-and-laura/

http://railsgrrls.tumblr.com/
especially: http://railsgrrls.tumblr.com/post/59391220574/blast-from-the-past-1st-demo-at-soundcloud
http://railsgrrls.tumblr.com/post/55865807738/soundcloud-interview-with-railsgrrls
http://railsgrrls.tumblr.com/image/53275132927

**Comment by anikalindtner** [comment]
mentions: 
http://teamspree.github.io/blog/2013/08/09/day-number-20/
http://teamspree.github.io/blog/2013/08/02/day-number-15/
http://teamspree.github.io/blog/2013/08/01/day-number-14/
http://teamspree.github.io/blog/2013/07/15/hello-octopress/

**Comment by anikalindtner** [comment]
twitter:
https://twitter.com/RailsGrrls/status/390807520760971265
https://twitter.com/RailsGirlsSoC/status/371982999614935040
https://twitter.com/RailsGrrls/statuses/370550748326551552
https://twitter.com/ninabreznik/statuses/362902830358605825
https://twitter.com/RailsGrrls/statuses/358197565512093696

**Comment by svenfuchs** [comment]
Wow, that's a lot of stuff. Thanks, @anikalindtner 

I particularly like these:
- screenshot of https://twitter.com/ninabreznik/statuses/362902830358605825
- http://railsgrrls.tumblr.com/post/59391220574/blast-from-the-past-1st-demo-at-soundcloud
- http://blog.soundcloud.com/2013/07/19/rails-girls-summer-of-code-welcoming-nicole-and-laura
- http://2013.railsgirlssummerofcode.org/blog/meet-team-rails-grrls

I guess that's enough for external references, isn't it?

Who's gonna work on the text?

**Comment by carpodaster** [comment]
I think it's important not to suggest that you have to be a SoundCloud with a huge host of developers to support RGSOC as a coaching company.

I asked @berlintam if she remembers a particular article that illustrates that point for a smaller company: maybe we could include [this article](http://highwaytorails.tumblr.com/post/60364788539/day-47-5-9-2013-testing-our-matcher) as well?

(I agree with what was said at the kickoff meeting about sponsoring companies, though: they should get the most attention)

**Comment by FloorD** [comment]
Maybe if I get anynines to say 'yes' quickly, that might be a good example.
We're about 10 of us only (admittedly backed by Avarteq, but still - that's
about 30-40 people)... Should I nudge?

**Comment by anikalindtner** [comment]
Nudge nudge!

**Comment by svenfuchs** [comment]
nudge nudge :)

**Comment by sareg0** [comment]
I am working on a text for this. Should be done with a draft soon. Is reviewing drafts in issue acceptable, or should I past in elsewhere?

**Comment by svenfuchs** [comment]
@sareg0 i think this is so urgent that if you can come up with a draft that you feel is good enough for publishing (i.e. better than the current, empty page) then just publish it via a pull request, and we can discuss improvements on the pull request. put a strong call to action to the top. wdyt?

**Comment by sareg0** [comment]
yup sure thing. I will publish within one hour then, and we will make improvements later

**Comment by anikalindtner** [comment]
grreat work! <3

what i'd think is still missing:

[x] an overview structure like for the faq's
[x] the question HOW you can get a coaching company (can they assign themselves in the app @svenfuchs?) and the answer (community mailing list, twitter, (app))
[x] and we need to shorten it still, i think people will just not read it.

**Comment by svenfuchs** [comment]
@anikalindtner wait, you've just given a todo list and now you closed the issue? i'm confused :)

I agree it should be shorter overall. 

Companies can't be "approved" as a coaching company. The only thing they can do is be part of the application their team(s) submit(s). Now when this application gets selected they'll be a coaching company.

Just like students looking for pairs, and coaches offering help, prospective coaching companies can announce themselves as such so that students can find them.

Does that make sense?

**Comment by anikalindtner** [comment]
@svenfuchs i just completed all my issues on the to-do-list. that's why it's done :) 

hmmm no, what i meant is that a coaching company can add them self to our community saying "hosting space" or sth. instead of "looking for a pair" etc.

![screen shot 2014-03-20 at 4 16 10 pm](https://f.cloud.github.com/assets/1711357/2473579/a221d6e2-b042-11e3-9699-264a652bb89c.png)

**Comment by svenfuchs** [comment]
Ah, gotcha
