### ISSUE TITLE
Reds

### ISSUE THREAD

**Issue by thatbettina** [rails-girls-summer-of-code/summer-of-code-2014#16]
On some pages there are different reds used in the header, footer, buttons: http://railsgirlsberlin.github.io/summer-of-code/contact.html

**Comment by lislis** [comment]
True. The different reds are most likely a result from the small  navigation bar being transparent on the first page and then trying to match the transparent color.
I wanted to do some css cleanup this week and I'll fix it then.

**Comment by thatbettina** [comment]
That would be great to have a cohesive look.

**Comment by lislis** [comment]
Closed. Commit: 86a243a498774a90d24f1734f06fd46cd3743c73

**Comment by thatbettina** [comment]
Thanks, Lisa, for taking care of that!

On Tue, May 28, 2013 at 2:53 PM, Lisa P notifications@github.com wrote:

> Closed. (I don't know how to reference to commit)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RailsGirlsBerlin/summer-of-code/issues/16#issuecomment-18548183
> .

## 

Bettina Shzu-Juraschek
Fuldastraße 19-20
12045 Berlin

+49 (0)163 164 7045
bettina.shzu@gmail.com
