### ISSUE TITLE
Application guide

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#160]
Hey @sareg0 

The application guide is really good: http://railsgirlssummerofcode.org/application-guide/

One nitpick: The opening feels somewhat harsh to me. Wdyt about 
- Changing the title to "How to apply?
- Then adding an opening paragraph saying something like "This guide gives you all the information you need to apply for Rails Girls Summer of Code via our application form (link to http://teams.railsgirlssummerofcode.org/application, still needs to be deployed)
- And changing "You must be eligible" to a question like "Who is eligible to apply?"

**Comment by svenfuchs** [comment]
Also, maybe we could move the ToC to the sidebar?

**Comment by sareg0** [comment]
Sure. I will make those changes along with the retirement of the projects page and transfer of info to applicaton guide (#156).
- [x] change the title 
- [x] add opening paragraph
- [x] change "You must be eligible" to a question like "Who is eligible to apply?"
- [x] reformat text to fit new structure of text
- [ ] add button or link to application form

cannot yet link in application form as not yet ready. Needs to be launched first.

**Comment by sareg0** [comment]
perhaps we could close this anyway, and create new issue for the application form, as it will involve a launch of some kind.

**Comment by svenfuchs** [comment]
@sareg0 looks perfect now :)
