### ISSUE TITLE
All things conferences

### ISSUE THREAD

**Issue by FloorD** [rails-girls-summer-of-code/summer-of-code-2014#168]
When we're adding sponsor logo's to the site we should also add conference logo's. I've been collecting the logo's for all conferences sponsoring tickets. I can take this on.

**Comment by sareg0** [comment]
@FloorD where were you thinking about putting these logos. I am just curious.

**Comment by FloorD** [comment]
@sareg0 just beneath the sponsor logo's, much like last year.

**Comment by FloorD** [comment]
I wrote a preliminary post about the conference tickets: https://gist.github.com/FloorD/1ced528f9541ce456530

Then, Rulu takes place June 19-20 in Lyon, France and RedDotRubyConf June 26-27 in Singapore. We would have 2 tickets for both conferences. I would send a short email to our alumni to raffle these out (as the 2014 program has not started yet by then but the conferences would still love to support diversity at their conference):

<Free tickets for RedDotRuby (Singapore ) and Rulu (France)>

Hi there!

It's your Rails Girls Summer of Code team checking in. Hope you are doing awe-some. 
Talking to conference organizers to give away free tickets to their conference for Rails Girls Summer of Code 2014 students, a number of the events will actually take place before the official program. RedDotRuby (June 26-27, Singapore) and Rulu (June 19-20, Lyon, France) are both giving away 2 tickets. 4 tickets in total, we would love to raffle them out to you. Let us know if you are interested in going to either Singapore or Rulu before May 25 12:00 CEST, we will inform the winners shortly after that via email.

Have a great day,
the Rails Girls Summer of Code team 

@anikalindtner who had the list of email addresses of last year's students again?

**Comment by FloorD** [comment]
@pxlpnk do you have a list with the email addresses of last year's students for me. That would rock. <3

**Comment by berlintam** [comment]
I just want to make sure that volunteer teams will also be included in the raffle in the same way that sponsored teams are. After talking w/ @svenfuchs , I became aware that last year, sponsored teams got first dibs at conference tickets, and then volunteer teams got the extras. It would be cool if this is not the case this year.

**Comment by FloorD** [comment]
I would not see why we would make that difference in the first place. I am
with you on this one.

**Comment by svenfuchs** [comment]
:+1: 

The reason for making that difference last year was that quite a few volunteering teams had turned inactive at that point.

**Comment by FloorD** [comment]
Fair enough point

**Comment by FloorD** [comment]
http://railsgirlssummerofcode.org/blog/2014-06-09-conference-tickets/ the post is out (and so is the email to last year's students), next I'll add the conference logo's (tonight).

**Comment by FloorD** [comment]
---

title: "Get your ticket to one (or more!) of these great conferences"
layout: post
created_at: Thu May 22 2014
permalink: blog/2014-07-22-conferences
current: blog
author: Floor

## twitter: RailsGirlsSoc

Get your twitter clients ready and join the rafflemania! 

Like last year, a number of exciting conferences have offered free (team) tickets for you - the Rails Girls Summer of Code students. We heard wonderful stories from our students last year about how they made new friends, valuable connections, learned heaps and had tons of fun. 

So we couldn't help but do it again! By now, we have 26 tickets to 13 amazing conferences and we're still adding more. 

Since some of them already take place mid-program, we decided to do an early raffle-out now, followed by a second one later this summer. So, IF you end up empty-handed, don't worry, you will get another shot! ;)

**How to get your hands on those awesome tickets**
We need you to tweet using your Rails Girls Summer of Code team Twitter account which conferences you'd like to attend - ordered by 1st choice, 2nd choice etc - followed by the #rgsoc hashtag. For example: 
_We would love to attend @arrrrcamp, @eurucamp and/or @rulu via #rgsoc_ 
(and alternatively add #wishfulthinking #LOL). 

By sending the tweet you automagically take part in the competition. Make sure you send your tweet by Friday July 25 12:00 (AM) CEST. We'll announce the winners shortly after.

You can choose from any of the below mentioned conferences. 

**What to do at the conference?**
First of all, we want you to be amazed and inspired. A conference is one of the best places to learn heaps of stuff and talk to wonderful people. 

Additionally, why not amaze the other attendees? We would love for you to share your Summer of Code story and spread the word to even more seasoned programmers about the great opportunities of the Rails Girls. Many conferences have slots for lightning talks. In a next post we'll give you some tips & tricks on how to ace a 5 minute talk like that.

**Here are the conferences of the first raffle:**

[**eurucamp**](http://2014.eurucamp.org/)
August 1-3
Berlin, Germany
2 tickets

[**Burlington Ruby Conference**](http://2014.eurucamp.org/)
August 1-3
Burlington, VT
4 tickets

[**Steel City Ruby**](http://steelcityruby.org/)
August 15-16
Pittsburgh, PA
2 tickets

[**Madison Ruby Conference**](http://madisonruby.org/)
August 22-23
Madison, WI
2 tickets

[**Frozen Rails**](http://2014.frozenrails.eu/)
September 11-12
Helsinki, Finland
2 tickets

[**Barcelona Ruby Conf**](http://www.baruco.org/)
September 12-14
Barcelona, Spain
2 tickets

[**The Strange Loop**](https://thestrangeloop.com/)
September 17-19
St. Louis
2 tickets

[**Ruby DCamp**](http://rubydcamp.org/)
October 10-12
Prince William Forest Park, VA
2 stipends

[**Rails Israel**](http://railsisrael2014.events.co.il/speakers-list)
November 4-5
Tel Aviv, Israel
2 tickets

[**Arrrrcamp**](http://2014.arrrrcamp.be/)
October 2-3
Ghent, Belgium
2 tickets

[**Polyconf**](http://polyconf.com/)
October 30-31
Poznan, Poland
2 tickets

[**GoTo Conference**](http://gotocon.com/berlin-2014)
November 6-7
Berlin, Germany
2 tickets

Good luck!

**Comment by FloorD** [comment]
WIP!

The teams and their conference(s), sorted by preference:

**[Participate](http://teams.railsgirlssummerofcode.org/teams/6)**
Frozen Rails
Arrrrcamp

**[Aria](http://teams.railsgirlssummerofcode.org/teams/5)**
Strangeloop

**[code_padawans](http://teams.railsgirlssummerofcode.org/teams/2)**
Frozen Rails
Arrrrcamp
Polyconf

**[Species+](http://teams.railsgirlssummerofcode.org/teams/12)**
arrrrcamp
GoToConference 
polyconfhq 

**[Instructure (LTI)](http://teams.railsgirlssummerofcode.org/teams/8)**
Madison Ruby

**[RapidRailsGirls (RapidFTR)](http://teams.railsgirlssummerofcode.org/teams/14)**
baruco
polyconf
arrrrcamp

**[Bundler ATL](http://teams.railsgirlssummerofcode.org/teams/4)**
Madison Ruby

**[Speakerinnen](http://teams.railsgirlssummerofcode.org/teams/18)**
eurucamp 

**[Migraine (Migraine Tracker)](http://teams.railsgirlssummerofcode.org/teams/17)**

**[Omnia Extares](http://teams.railsgirlssummerofcode.org/teams/7)**

**[BrowserSpree](http://teams.railsgirlssummerofcode.org/teams/9)**

**[Rubinius](http://teams.railsgirlssummerofcode.org/teams/3)**

**[SeeMeSpeak](http://teams.railsgirlssummerofcode.org/teams/13)**

**[Mutants](http://teams.railsgirlssummerofcode.org/teams/1)**

**[SpreeGirls](http://teams.railsgirlssummerofcode.org/teams/10)**

**[Standard Librarians](http://teams.railsgirlssummerofcode.org/teams/11)**

**Comment by FloorD** [comment]
@svenfuchs we are waiting for team speakerinnen who are in the office anyway and then we should do the raffle-out (hope you have time). That way the teams will know by tomorrow and can plan their trips right away. 

I can publish a blog about it tomorrow, notify all the teams by email AND tell the conferences (also the ones that didn't get applications. some are later on in the program - and can join in a second round). I'll make sure the conf organizers get to know the students so they can help them secure a lightning talk slot :)

**Comment by FloorD** [comment]
YAY the raffle out ended in:
(supervisors! pssst! it's a surprise until tomorrow morning!)

Aria - Strangeloop
Speakerinnen - eurucamp
Instructure - MadisonRuby
Participate - FrozenRails
code_padawans - arrrrcamp
RapidRailsGirls - polyconf AND BaRuCo
Species+ - GoToConf

**Comment by bjonord** [comment]
:+1:

**Comment by FloorD** [comment]
**email to the winning teams:**

Hi there team!

You have participated in the Big Conference Raffle-Out Part One and we're excited to tell you that **you've won 2 (!) tickets for XXX**.

Please let us know if you will DEFINITELY go and we'll make sure the conference organizers make badges for you. 

If you can't make it - don't feel bad, your ticket will find a way to one of the other teams, to one of our lovely coaches, mentors, organizers or Rails Girls alumni from the area that they conference is at. Make sure you let us know asap. 

We highly encourage you to take on a lightning talk at the conference you're attending and we will publish a post on the Rails Girls Summer of Code blog shortly, filled with tips and tricks on how to ace such a 5 minute talk (or at least to fight the stages fright a little ;)).

<3
The Rails Girls Summer of Code team

**Comment by anikalindtner** [comment]
I would put in that we also need a cancellation asap, if they are not able to go. else: +1

**Comment by FloorD** [comment]
*\* email to the conferences**

Hi there XX organizers,

Yesterday we had our first round of the conference tickets raffle-out and Team XX claimed the two tickets to your conference! You can reach XX and XX via their email addresses: xx@xx.com and xx@xx.com.

We highly encourage our students to give a lightning talk at your conference, might there be a slot available. Could you help them secure the chance to chat about the Open Source Project they are working on (and a bit about Rails Girls Summer of Code in general)?

Thanks again for supporting our program! 

Have a great day,
Floor

---

Hi there XX organizers,

Yesterday we had our first round of the conference tickets raffle-out and as your conference is still a while away, the 2 tickets you offered are still up for the grabs. We would love to include you in the second round to give our students the chance to figure out flight and accommodation plans a bit better. Alternatively, you (or we) could offer them to our volunteering coaches and organizers, or to a Rails Girls chapter close to you. How does this sound to you?  

Thanks again for supporting our program! 

Have a great day,
Floor

---

Hi there XX organizers,

Yesterday we had our first round of the conference tickets raffle-out and the tickets you offered are still up for the grabs.You (or we) could offer them to our volunteering coaches and organizers, or to a Rails Girls chapter close to you. How does this sound to you?  

Thanks again for supporting our program! 

Have a great day,
Floor

**Comment by FloorD** [comment]
WIP

---

title: "And the conference tickets go to..."
layout: post
created_at: Tue July 29 2014
permalink: blog/2014-07-29-tickets-raffle
current: blog
author: Floor

## twitter: RailsGirlsSoc

You all turned to Twitter and the results are in! "And the conference tickets go to..."

[Participate](http://teams.railsgirlssummerofcode.org/teams/6) - FrozenRails

[Aria](http://teams.railsgirlssummerofcode.org/teams/5) - Strangeloop

[code_padawans](http://teams.railsgirlssummerofcode.org/teams/2) - arrrrcamp

[Species+](http://teams.railsgirlssummerofcode.org/teams/12) - GoToConf

[Instructure (LTI)](http://teams.railsgirlssummerofcode.org/teams/8) - MadisonRuby

[RapidRailsGirls (RapidFTR)](http://teams.railsgirlssummerofcode.org/teams/14) - polyconf AND BaRuCo

[Speakerinnen](http://teams.railsgirlssummerofcode.org/teams/18) - eurucamp

CONGRATULATIONS!

IF you ended up empty-handed, don't worry, you will get another shot as **we'll be adding new conferences for a second round of ticket raffling**. 

**And now what?**
Well, now you can all start planning your trips and accommodation. Let us know if we can connect you to the local Rails Girls community to make your stay even more fun. 

Then: enjoy the conference! Additionally, why not amaze the other attendees? We would love for you to share your Summer of Code story and that's why we wrote up some [handy nuggets to help you past your initial stage fright](http://railsgirlssummerofcode.org/blog/2014-07-29-talk-tips/) ;) 

**Thank you to all our round 1 conferences**

[eurucamp](http://2014.eurucamp.org/), [Burlington Ruby Conference](http://2014.eurucamp.org/), [Steel City Ruby](http://steelcityruby.org/), [Madison Ruby Conference](http://madisonruby.org/), [Frozen Rails](http://2014.frozenrails.eu/), [Barcelona Ruby Conf](http://www.baruco.org/), [The Strange Loop](https://thestrangeloop.com/), [Ruby DCamp](http://rubydcamp.org/), [Rails Israel](http://railsisrael2014.events.co.il/speakers-list), [Arrrrcamp](http://2014.arrrrcamp.be/), [Polyconf](http://polyconf.com/), [GoTo Conference](http://gotocon.com/berlin-2014)

Have fun!

**Comment by FloorD** [comment]
Emails to the students are out, emails to the conferences that could give away tickets, those who could not. Up next: emailing conference for the second round. On my list:

[FutureStack](http://futurestack.io/) 
futurestack@newrelic.com

[RubyConf Portugal](http://rubyconf.pt/) 
hello@rubyconf.pt
@rubyconfpt

[Keep Ruby Weird](http://keeprubyweird.com/) - ping Terence
organizers@keeprubyweird.com
@keeprubyweird

[RubyConf San Diego](http://rubyconf.org/)
rubyconf@rubycentral.org 
@rubyconf

[RubyCaribe](http://www.rubycaribe.com/)
@rubycaribe
http://rayhightower.com/contact/

[RubyConf Australia](http://www.rubyconf.org.au/) - 2015
organisers@rubyconf.org.au
@rubyconf_au

[RubyConf Philippines](http://rubyconf.ph/) - 2015
crigor@rubyconf.ph

[RailsConf Chicago](http://www.railsconf.com/) - 2015
railsconf@rubycentral.org
@railsconf

[RubyConf Argentina](http://rubyconfargentina.org)
@RubyConfAR

RailsIsrael will participate again (2 tickets) in the second round.

If you think of any more, let me know! 

**Suggestions:**

[RubyDay](http://www.rubyday.it) - via Laura

[Oredev](http://oredev.org/) - via björn

**Comment by FloorD** [comment]
[RubyConf Portugal](http://rubyconf.pt/) 
hello@rubyconf.pt
@rubyconfpt
3 tickets

> > "We'll also be having a Rails Girls Braga in the days before the conference. It would be great to have your students pass some motivation to the Rails Girls participants."

---

[Keep Ruby Weird](http://keeprubyweird.com/) - ping Terence
organizers@keeprubyweird.com
@keeprubyweird

> > A scholarship program already in place - http://keeprubyweird.com/scholarships/apply/.
> > they set aside 2 scholarships for rgsoc

---

[RailsConf Chicago](http://www.railsconf.com/) - 2015
@railsconf

[RubyConf San Diego](http://rubyconf.org/)
rubyconf@rubycentral.org / abby@rubycentral.org
@rubyconf

> > Opportunity Scholarship program

---

[RubyCaribe](http://www.rubycaribe.com/)
@rubycaribe
rth@wisdomgroup.com

> > two scholarships
> > As part of the scholarship application, the applicant will submit an app via GitHub. Judges will include members of the faculty at UWI. Applicants need to live in Barbados...

---

[Oredev](http://oredev.org/)
per@oredev.org

> > two free tickets to Øredev (a ticket costs around $1500)

---

[CSSconf EU](http://2014.cssconf.eu/)
2 free tickets to CSSconf EU
contact@cssconf.eu

---

**Comment by FloorD** [comment]
DRAFT

---

title: "Claim a ticket to the conference of your choice (and learn tons)"
layout: post
created_at: Fri Aug 22 2014
permalink: blog/2014-08-22-conferences
current: blog
author: Floor

## twitter: RailsGirlsSoc

[As promised](http://railsgirlssummerofcode.org/blog/2014-07-24-conferences/), we have a whole new round of great-conferences-you-can-visit-for-free! This time around we have both tickets and scholarships to draw your attention to. We've listed what you should do to get either of those in the list below. Good luck!

# Tickets

[**CSSconf EU**](http://2014.cssconf.eu/) ([@cssconfeu](https://twitter.com/cssconfeu) on Twitter) takes place in Berlin, September 12. We have _2 tickets_ to give away. 

[**The Strange Loop**](https://thestrangeloop.com/) ([@strangeloop_stl](https://twitter.com/strangeloop_stl) on Twitter) takes place September 17-19 in St. Louis. We have _2 tickets_ to give away.

[**RubyConf Portugal**](http://rubyconf.pt/) ([@rubyconfpt](https://twitter.com/rubyconfpt) on Twitter) takes place October 13th - 14th in Braga. We have _3 tickets_ to give away. RubyConf Portugal will also be organizing a Rails Girls Braga in the days before the conference, which you'd be very welcome to attend and coach at. 

[**Oredev**](http://oredev.org/) ([@oredev](https://twitter.com/oredev) on Twitter) takes place November 4-7 in Malmö (Sweden) and we have _2 tickets_ (a ticket costs around $1500) to give away!

[**Keep Ruby Weird**](http://keeprubyweird.com/) ([@keeprubyweird](https://twitter.com/keeprubyweird) on Twitter) takes place Friday, October 24th in Austin. They set aside _2 tickets_ for Rails Girls Summer of Code. 

[**RubyConf Philippines**](http://rubyconf.ph/) ([@RubyConfPH](https://twitter.com/RubyConfPH) on Twitter) takes place March 27-28, 2015 on Boracay Island and we have _2 tickets_ to give away.

_For all the above conferences we need you to tweet from your team Twitter account or from your personal Twitter account, what conference(s) you would like to attend - mentioning the conference' Twitter handle *_and*\* using the #rgsoc hashtag.*

# Scholarships

[**rejectjs**](http://rejectjs.org/) offers one ticket to their wonderful conference, plus covers travel expenses of up to 150€ via their [Community Package](http://rejectjs.org/#community-package). Do mention that you are a Rails Girls Summer of Code student!

Both [**RailsConf Atlanta**](http://www.railsconf.com/), taking place April 22-25 (yes, 2015), and [**RubyConf San Diego**](http://rubyconf.org/), taking place November 17-19 this year still, have an 'Opportunity Scholarship Program' in place. We will share application details with you shortly. 

# What to do at the conference?

First of all, we want you to be amazed and inspired. A conference is one of the best places to learn heaps of stuff and talk to wonderful people. 

Additionally, why not amaze the other attendees? We would love for you to share your Summer of Code story and spread the word to even more seasoned programmers about the great opportunities of the Rails Girls. Many conferences have slots for lightning talks. Not sure how to tackle the task? We have just [the blog post](http://railsgirlssummerofcode.org/blog/2014-07-29-talk-tips/) for you!

And now go, go, GO for those tickets.
Good luck!

**Comment by alicetragedy** [comment]
:thumbsup: 

Did you get any replies from the people at Ruby Day, @FloorD? Also I find the "so-called scholarships" phrase a bit weird - it makes it sound a bit negative somehow - maybe replacing it with "scholarship programs" might be best? Can't think of another term that could be used. The English language has failed me. :cat:

**Comment by FloorD** [comment]
Oops didn't want it to sound negative - just figured that some people might not know what a scholarship entails... Please help me rephrase!
Waiting for an update from Sante (Ruby Day) but have just nudged him.

**Comment by alicetragedy** [comment]
oh yeah, that actually makes sense.. I suppose that if what the scholarships entail is similar at all the conferences that offer it, we could put it directly in the intro (and have faith in the fact that the interested students will click on links and take a look at the detailed scholarship descriptions). 

Alternatively, we could have "Tickets" and "Scholarships" subheadings, with a short description of what that actually means under the scholarship subheading.. for example financial support to attend the conference, help to find cheap accommodation, or whatever else is offered - just to give them an idea of what it means. 

If it's not too "dringend" I can take a look at it in the early afternoon - after work (:

**Comment by FloorD** [comment]
Not 'dringend' at all, waiting to hear back from RubyConf and Ruby Day first, so take your time. Thanks @alicetragedy

**Comment by alicetragedy** [comment]
no problem! maybe I am just overly sensitive to it sounding negative but if we can find a good way to rephrase it, it would be great :) I'll do that later!

**Comment by anikalindtner** [comment]
"RubyConf Australia (@rubyconf_au on Twitter) takes place February 19-21 in Sydney, Australia . We have - to give away."
- the number of tickets is missing.. is that still in progress?

I'd also divide the blog post more by using titles within.
like 

### Tickets
- bla
- bla
- bla

#### How to get them
- blubb

### Scholarships
- bla

#### How to get them
- blubb

ah... and whil typing i see that @alicetragedy already pointed that out hihi. well two minds..

**Comment by anikalindtner** [comment]
ah ok, and my other question is also already solved (about rubyconf). note to self: read comments before. :P

**Comment by hone** [comment]
@FloorD railsconf 2015 is in Atlanta. Chicago was this year. What's the difference b/t an opportunity scholarship and a ticket you're talking about here? For Keep Ruby Weird, we've set aside two tickets from our scholarship program for RGSoC, but I thought you would just tell us who they were, but we can do it the other way around too. Also, the scholarship tickets is only way to get into the conference now since it's sold out :D

**Comment by FloorD** [comment]
@hone ok great, then I just put it up as tickets, not scholarships. Will update the draft in a minute!

**Comment by anikalindtner** [comment]
@FloorD is this ready to share now? I just keep seeing the word draft and don't dare ;)

**Comment by FloorD** [comment]
hahahaha delete 'draft', update the date and everything should be fine :)

**Comment by FloorD** [comment]
@sareg0 could you post this in a blog format + a party picture (featuring a cat, naturally)

**Comment by anikalindtner** [comment]
@FloorD i'm sorry, but i had to delete the comment, i'll put it in the private organizer's repo, so nobody can see it before we announce it. sorry about this,  i only realized now that we are not in the orga repo..

here is the link: https://github.com/rails-girls-summer-of-code/organization/issues/66

**Comment by sareg0** [comment]
@FloorD  on it

**Comment by FloorD** [comment]
Blog post is out, tweet is out, emails to orgs is out and emails to winners is out! Done!

**Comment by sareg0** [comment]
and closed.
