### ISSUE TITLE
add timeline to website

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#170]
1. March: Open applications!
   March: Crowdfunding start
2. May: Close applications!
   03.-04. May: Rank applications
   05.-06. May: Acceptance letters
   June: Preparations
3. July: Start RGSoC 2014!

**Comment by svenfuchs** [comment]
Do eet :)

**Comment by anikalindtner** [comment]
the most important one is done for now: 
![screen shot 2014-03-19 at 12 17 02 am](https://f.cloud.github.com/assets/1711357/2454860/7dcd5e56-aef3-11e3-82b4-f2c5f330389e.png)
 the rest will get into the sidebar

**Comment by svenfuchs** [comment]
awesome!

**Comment by anikalindtner** [comment]
done
