### ISSUE TITLE
Clarify Rails Girls Summer of Code is a global event

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#173]
![image](https://f.cloud.github.com/assets/2208/2455715/750b2dae-af05-11e3-990b-95a2d850edca.png)

I guess the homepage already states this by saying "worldwide", but maybe this can be overlooked too easily. This question pops up quite often.

![image](https://f.cloud.github.com/assets/2208/2455728/b0426158-af05-11e3-9b36-2d7f8cafda35.png)

What's a good solution?

**Comment by runlevel5** [comment]
IMHO we should contact the RailsGirl group in each city and let them spread the word, maybe having a google map with pin dropped places where local group is aware of this event?

**Comment by tjmcewan** [comment]
it's fundamentally difficult because it's not summer everywhere at the same time.  maybe Rails Girls Global "Summer" of Code. :P

To clarify, I think most people will judge it by the name.  So without changing the name, there's not much more that can be done.

**Comment by willrax** [comment]
That would be a good idea. If I'd have visited the front page I probably could have answered my own question by seeing that. I was led to the blog via a tweet someone in Australia made so bypassed it.

**Comment by svenfuchs** [comment]
@joneslee85 that's a cool idea. We're trying to update the global RG organizers mailing list, and ask for support.

@tjmcewan @willrax interesting. Thanks for the input!

I would have expected that devs on the southern hemisphere are used to this meaning of "summer" from Google and Ruby Summer of Codes. Renaming will be hard ... and the name is already way too long (so it gets abbreviated to RGSoC frequently, which is pretty ugly, too).

Maybe we could add some sort of badge using the word "Global" on the layout/all pages?

**Comment by runlevel5** [comment]
I think of a rolling marquee badge with all countries flags

**Comment by anikalindtner** [comment]
I like the idea of especially reaching out to every local rails girls chapter. we can reach them via the global list, but induvidually may be more effective - although it will be some work, since there is (to my knowledge) no global contact list for every chapter... but yeah let's do that!

**Comment by anikalindtner** [comment]
oh and i would change "summer 2014" to "july-sep 2014" on the front page, that makes it a bit clearer, since "summer" can mean any time depending on the country you are in.

and also we could use many many more pictures from workshops all over the world for the frontpage and make a "mosaic"-like header.

**Comment by FloorD** [comment]
I can help reach out Anika, we we can distribute the workload.

**Comment by anikalindtner** [comment]
@FloorD :yellow_heart: :yellow_heart: :yellow_heart:
