### ISSUE TITLE
Nav Item "Get Involved" for sponsors, coaches etc.

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/summer-of-code-2014#182]
In the long run contains:
- [x] Sponsoring 
- [x] Coaching
- [x] Coaching Company
- [ ] Donate

For now: Gonna set up Nav item, add Coach Guide and link "Coaching comanies" page.

**Comment by sareg0** [comment]
I just took out 'host a team', cause coaching companies are sort of that. They are 'host companies' so zu sagen

**Comment by katrin-k** [comment]
aah, i understood hosting as an extra option like this coworking space in sydney. but true, even then it's kinda the same.
