### ISSUE TITLE
Set up forms for projects, students, coaches, companies

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#2]
We need to decide on a technology. @NerdBabe mentions that RailsGirls Berlin uses Google Forms for applications for workshops. @phenriettak offered using the RailsGirls [Wufoo](http://www.wufoo.com) account. I personally never used any of them. Advantages/disadvantages? @NerdBabe? @phenriettak?

Should also come up with lists of questions/information that we want to collect from the groups: projects, students, coaches, companies

**Comment by nanoparsec** [comment]
Hey,
I have created a tab on our sheet for collecting questions for the forms:
https://docs.google.com/spreadsheet/ccc?key=0AjmbYjwdIlFZdHVaRFRmelNDdm50LTZ1bW5lTWRGUUE#gid=6
I added some Questions that came in my mind.

**Comment by nanoparsec** [comment]
I like google forms. But I don't mind if we use wufoo instead. Advantage of google forms: easy to use, free, can be shared with everyone of our orga task force.

Best

Ute

**Comment by phenriettak** [comment]
Google forms could be more accessible! 

And we have to pay for wufoo :D 

xo H

On Apr 2, 2013, at 2:54 PM, CayCee wrote:

I like google forms. But I don't mind if we use wufoo instead. Advantage of google forms: easy to use, free, can be shared with everyone of our orga task force.

Best

Ute

**Comment by nanoparsec** [comment]
so, lets use googleforms, okay? ^^ I will take the setup task thing...

2013/4/2 Pia Henrietta Kekäläinen notifications@github.com

**Comment by svenfuchs** [comment]
@NerdBabe do you think the projects form will be ready by sunday? we might want to tweak one question or the other a bit, based on feedback from the group. So it'd be even more awesome if you could have a first version of the form before sunday, maybe even tomorrow? do you think that'd be possible? :)

**Comment by nanoparsec** [comment]
Yes, that is possible :) I will set them up and post the links here :)

2013/4/11 Sven Fuchs notifications@github.com

**Comment by nanoparsec** [comment]
Hey, 
Here are the links for the other forms: 
coaches: https://docs.google.com/forms/d/1vcojeBJg--VraWkojnNB2MUDc4rd6rX__3w4Kz8oQM4/viewform
students: https://docs.google.com/forms/d/158MlfRepVVZh9NjskR7-fuNJz5EsgzRnhrmTD94HXwY/viewform
companies: https://docs.google.com/forms/d/1EIiv3Xukep6u4Myna2tXo0Z-mirZswNnoqmscTWBGmw/edit

I shared the answer-spreadsheets with all of you.

If there are things you want to have changed regarding the form, let me know. I will update them then.

Best

Ute
