### ISSUE TITLE
Student projects guide or FAQ: requirements for projects

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#205]
There should be a page that answers this question: https://twitter.com/ZustMust/status/452839463308103680

Or do we have one?

**Comment by BanzaiMan** [comment]
I'm guessing this is it: http://railsgirlssummerofcode.org/students/application/#8

**Comment by svenfuchs** [comment]
@BanzaiMan yeah, that might be a good place, but I guess we could answer the question ("Are students suppose to come up with their own idea for the project or to work on one of the Githubs' propositions?") more explicitly.

Maybe:

"You can pick one of the proposals, or you can find your own project. Having an existing project (which has real users) and well-know projects (which has exposure) is preferred, but not required."

I also seem to remember that there was another place where something like this got mentioned, but I can't find it :)

**Comment by anikalindtner** [comment]
I think we can close this now for this year.
