### ISSUE TITLE
Use SASS & Compass

### ISSUE THREAD

**Issue by josepjaume** [rails-girls-summer-of-code/summer-of-code-2014#21]
Hi!

The CSS files are starting to look a little unmanageable, so I'd suggest to look to a CSS precompiler like SASS and even better, a framework like compass. They can be easily integrated with Jekyll:

https://github.com/chriseppstein/compass/wiki/Jekyll-Integration

SASS comes with awesome stuff like better media query management, rule nesting, functions like `opacify` or `desaturate`, variables, mixins... Check it out:

http://sass-lang.com/

Compass as a framework also provides grids, automatic prefixing for multiple browsers...

http://compass-style.org/

I would really give it a look since I suspect the `main.css` file will become unmaintainable in the short term.

Thoughts? Just a friendly advice, no criticism :)

**Comment by svenfuchs** [comment]
I think @lislis wanted to work on cleaning this up a bit. Could imagine she'd appreciate some help?

**Comment by josepjaume** [comment]
Of course! I implicitly meant that I'd help with this if you're ok with it :)

**Comment by lislis** [comment]
Hi there! I would love to use Sass/ Compass for the project :D 
I wasn't sure if it would work with Jekyll (I'm new to that, too) but it seems to be super easy!
If you can spare some time feel free to get things started.

**Comment by josepjaume** [comment]
Great! Actually compass & sass work with everything. In the worst case you just compile down to plain CSS and push it to the repo.

I'll get things started if I can find a moment :)
