### ISSUE TITLE
"Everything you ever wanted to know about volunteer teams" blogpost

### ISSUE THREAD

**Issue by berlintam** [rails-girls-summer-of-code/summer-of-code-2014#220]
suggestions welcome ( @svenfuchs @anikalindtner @katrin-k @sareg0 )
### Everything you ever wanted to know about volunteer teams

This year, RGSoC has accepted [six volunteer teams](http://railsgirlssummerofcode.org/blog/almost-final-team-list/)  in addition to ten sponsored teams. It’s an exciting development, and you may be wondering, what is a volunteer team, and how do I become one?

Volunteer teams, like sponsored teams were hand picked by the selection committee from the pool of applicants. The chosen teams showed enthusiasm and demonstrated that they have a good level of support. We really wanted these teams in the program, but sadly, we couldn’t sponsor them. Instead of leaving them out completely, we took a leap of faith, and asked if they wanted to do it anyway. Lucky for us, six of them said yes!
### So what is a volunteer team?

A volunteer team is the same as a sponsored team, with two main differences. First, as the name implies, they do not receive monetary support from RGSoC, so they need to be financially stable enough to support themselves over the summer. Second, because of the financial constraints, volunteer teams are only asked to work part time on their open source project. 

Aside from those two points, volunteer teams will participate in the summer of code and have the same experience as sponsored teams. They will:
- get access to the same support structure and benefits such as conference tickets
- document their daily work on their  [team log](http://railsgirlssummerofcode.org/students/team-log) and send in pictures/tweets
- give a lightning talk at a conference
- be assigned a supervisor
- connect to other students via the RGSoC chat
### How do I become a volunteer team?

This year's applications are closed and teams have been selected, ready to kick off on 1st of July. If you want to be considered as a volunteer team next year, send in an application when applications open and show us what you're made of!
### The team behind the teams

Volunteer teams also have a great support structure behind them. [Susanne Dewein](https://twitter.com/BibiBienenstich), [Tam Eastley](https://twitter.com/travelingtamm), and [Carsten Zimmermann](https://twitter.com/carpgezwitscher) will all be volunteer team supervisors. You may recognize those names from last year: Susanne and Tam were students with the volunteer team [Highway to Rails](http://highwaytorails.tumblr.com/), and Carsten was their coach. They bring with them this summer a wealth of first hand information about what it’s like to successfully complete a voluntary summer of coding ruby on rails.

**Comment by FloorD** [comment]
:+1:

**Comment by svenfuchs** [comment]
Awesome post!

I few comments:

> Second, because of the financial constraints, volunteer teams are only asked to work part time on their open source project.

Have we specified this more? I seem to remember "half-time", but I can't remember what the final consent was.

> - document their daily work in the form of a blog
> - regularly send in pictures/tweets from their team

I'd join these and say
- document their daily work on their [team log](http://railsgirlssummerofcode.org/students/log) and send in pictures/tweets from their team

... the pictures/tweets thing seems like a minor detail compared to the rest of the of the list

> Unfortunately it’s too late to become a volunteer team this year, as applications have closed and the selection process is done. If you want to considered as a volunteer team next year, submit an amazing application and show us what you’re made of!

Hmmm, the flow feels a bit like "tease ... tease ... tease ... oops, nevermind, doesn't work for you".

Maybe change this to

"This year's applications are closed and teams have been selected, ready to kick off on 1st of July. If you want to be considered as a volunteer team next year ..."

**Comment by berlintam** [comment]
Great suggestions.

As for time, I told the students that they should work 'at least part time' on their projects. I didn't specify this, and I realize I probably should have. To me this means 20 hours a week but I suppose it will have to be clarified more in detail with their supervisors at the start of the program. I don't know what this means for the blogpost thou... just leave as is for now?

**Comment by svenfuchs** [comment]
Why not just go ahead and say we expect "halftime", that's still slightly vague, and we start setting the expectation. People can then respond to that, should they have any issues, and we can deal with these.

**Comment by berlintam** [comment]
published!
