### ISSUE TITLE
Team log page

### ISSUE THREAD

**Issue by bastilian** [rails-girls-summer-of-code/summer-of-code-2014#221]
We need to restore the Team-Log page.

Can we just move the one from rails-girls-summer-of-code/summer-of-code-2013?
Is the text still right?

https://github.com/rails-girls-summer-of-code/summer-of-code-2013/blob/gh-pages/team-log.md

**Comment by svenfuchs** [comment]
@bastilian It's now here: http://railsgirlssummerofcode.org/students/log/

**Comment by bastilian** [comment]
Ah! perfect! :)
