### ISSUE TITLE
add team's site

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#225]
to show which wonderful people are involved in this year's rgsoc, it would be awesome to have a team-site, where we list all the organizers, supervisors, coaches, mentors, designers etc. who are running rgsoc this year. @bastilian can we pull that data out of the teams app so that any changes will be automatically updated and we don't have to have a static site? @ngkhanhlinh could you do a simple mockup of a design for such a site? and then @lislis could implement it?

**Comment by anikalindtner** [comment]
ideally we could pull that off before july first. wdyt? can we? would be so awesome
![awesomejump](https://cloud.githubusercontent.com/assets/1711357/3320217/3b3784ea-f728-11e3-9a69-9923c3060aa6.gif)

**Comment by lislis** [comment]
@anikalindtner well I'm not in town fom the 26th to the 7th so it should happen before that ;)
@bastilian can one query the teams app for some json?

**Comment by carpodaster** [comment]
@lislis That should be doable. What data do you need or how would you have stuctured? Anything special other than the public user attributes and a list of roles they have?

**Comment by bastilian** [comment]
@carpodaster do you want to take over rails-girls-summer-of-code/rgsoc-teams/issues/105? or should i?

**Comment by lislis** [comment]
@carpodaster well, all the information that should go on the teams page. I'm not really sure what should be included. I guess the public attributes should be just fine @anikalindtner ?

**Comment by carpodaster** [comment]
@bastilian I can do it tonight, sure

**Comment by bastilian** [comment]
@carpodaster ok, cool. thanks! i'll do the other ones @svenfuchs posted in slack.

**Comment by anikalindtner** [comment]
aweseome! yes, i think we only need the names and the picture. that should be enough. thank you so much \o/

**Comment by ngkhanhlinh** [comment]
I'm in! 

We still need a simple mockup design for this right? I'll work on this and post it tomorrow. Does that work @anikalindtner @lislis? :)

**Comment by anikalindtner** [comment]
@ngkhanhlinh sounds awesome! yes, just a simple mockup so that @lislis can implement it.

**Comment by carpodaster** [comment]
@lislis you can access the json here: http://teams.railsgirlssummerofcode.org/contributors.json
Ping me if you need anything else in that list.

**Comment by lislis** [comment]
@carpodaster awesome!

**Comment by ngkhanhlinh** [comment]
Here's the first draft mockup. 

Right now it only includes names and pictures but we can add twitter & github handle if needed. Any feedbacks? :)

![team-site-concept-1](https://cloud.githubusercontent.com/assets/4908043/3349074/02532b0e-f951-11e3-9103-93d9d0f88411.png)

**Comment by FloorD** [comment]
With a twitter handle and github thingie, I'd say: :+1: 
I like how there's some white space!

**Comment by svenfuchs** [comment]
Looks great! Go for it.

**Comment by lislis** [comment]
Heya! I'll try to have it done by tomorrow evening. I'd put the twitter and github handles centered below the name with icons. 
But one other thing: if people have two or more roles, should I list them multiple times or just once ?

**Comment by lislis** [comment]
@carpodaster can you add the twitter handles to the json?
also, some more things: there are a lot of duplicates and that does not look nice. Also some people don't have an image or a name, just a  github handle. For the image I could use a default one, but a name would be nice. 
@svenfuchs @anikalindtner

**Comment by carpodaster** [comment]
@lislis done in https://github.com/rails-girls-summer-of-code/rgsoc-teams/commit/a7b127cf06883bc6a6fbcd0023d368bd4ef52b54

Instead of `name` there is now `name_or_handle` that is also used internally on the teams app. It gives the name and falls back to the github handle.

**Comment by lislis** [comment]
@carpodaster not sure I understand correctly. If there is no `name` will I automatically get the `github_handle` or is this only concerning the teams app?
Edit: I got it, it's now called `name_or_handle` :)

**Comment by sareg0** [comment]
@anikalindtner is this one closed now? Or did we still need to make improvements on this page?

**Comment by anikalindtner** [comment]
nah, we can close it for now
