### ISSUE TITLE
RGSoC Berlin Kick-Off

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#226]
Please RSVP in a comment here, if you are coming to the BBQ at DaWanda's office July 1st, starting 6-7 PM (Windscheidstr. 18).

**Comment by anikalindtner** [comment]
me +1

**Comment by FloorD** [comment]
Me

**Comment by svenfuchs** [comment]
:+1:

**Comment by benjaminmateev** [comment]
Me

**Comment by carpodaster** [comment]
Yup :smile:

**Comment by nanoparsec** [comment]
me :)

2014-06-27 14:47 GMT+02:00 Anika notifications@github.com:

> me +1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/summer-of-code/issues/226#issuecomment-47339260
> .

## 

_--------------_
_nerdbabe_

_Personal Contact Information_
_Email: mail@nerdbabe.de mail@nerdbabe.de_
_Website: nerdbabe.de http://nerdbabe.de_
_Twitter: *nerdbabe
https://mail.google.com/mail/ca/u/0/https//:twitter.com/nerdbabe
*Github:_ NerdBabe https://github.com/NerdBabe

**Comment by roidrage** [comment]
:shipit:

**Comment by madziaf** [comment]
comming! +1

**Comment by sray** [comment]
me + 1

**Comment by lindaliukas** [comment]
me!

**Comment by jasonforal** [comment]
![yep!](http://cl.ly/image/450l2Y3h0c2w/hellyeah.gif)

**Comment by sareg0** [comment]
Me :)

**Comment by eljojo** [comment]
![Let's do this!](https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com/tumblr_liy7k0TTJW1qixleeo1_400.gif)

**Comment by berlintam** [comment]
yup!

**Comment by schultyy** [comment]
+1

**Comment by starkcoffee** [comment]
:squirrel:

**Comment by Bumbledebee** [comment]
Ich komme

**Comment by plexus** [comment]
✓

**Comment by miveronese** [comment]
- 1 :)

**Comment by sferik** [comment]
:rocket: :full_moon:

**Comment by chatulli** [comment]
looking forward to it :-)

**Comment by BriocheBerlin** [comment]
+1

**Comment by ctrlaltjustine** [comment]
✅

**Comment by nanoparsec** [comment]
i will bring a plus 1 with me.

Am Samstag, 28. Juni 2014 schrieb Justine :

> ✅
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/summer-of-code/issues/226#issuecomment-47427272
> .

## 

_--------------_
_nerdbabe_

_Personal Contact Information_
_Email: mail@nerdbabe.de mail@nerdbabe.de_
_Website: nerdbabe.de http://nerdbabe.de_
_Twitter: *nerdbabe
https://mail.google.com/mail/ca/u/0/https//:twitter.com/nerdbabe
*Github:_ NerdBabe https://github.com/NerdBabe

**Comment by kat-crumbs** [comment]
Me

**Comment by kilaulena** [comment]
yup

**Comment by alicetragedy** [comment]
:thumbsdown: so sad I can't make it, but have fun y'all :balloon:

**Comment by bjonord** [comment]
Can't make it. For several reasons, but the most obvious one is not being in Germany. :-(

**Comment by kaeff** [comment]
Love to join!

**Comment by rkh** [comment]
:+1:

**Comment by FrauBienenstich** [comment]
can't make it unfortunately :(

**Comment by chad** [comment]
I can't make it :poop:

On Mon, Jun 30, 2014 at 11:18 AM, Susanne Dewein notifications@github.com
wrote:

> can't make it unfortunately :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/summer-of-code/issues/226#issuecomment-47510845
> .

##

**Comment by drogus** [comment]
I'll be there! :D

**Comment by phenriettak** [comment]
me & linda yey!

**Comment by anikalindtner** [comment]
****_take your jackets with you, dear BBQ people,  it's open air!**_****
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:
