### ISSUE TITLE
Make teams activity page more public

### ISSUE THREAD

**Issue by berlintam** [rails-girls-summer-of-code/summer-of-code-2014#227]
The activities page in the teams app which shows all the blogposts from the teams is awesome, and it would be cool if the public knew about it so that they can keep up with all the students and read their blogs. I know that you don't have to be signed in to see it, but it's virtually impossible to find if you don't know how/from the rgsoc main page. 

My suggestion: make this part of the teams app a larger feature in the rgsoc website.

**Comment by svenfuchs** [comment]
:+1:

We had a link "Teams ->" in the top menu on the main page, which was removed earlier this year. And we had a link "Home ->" in the top menu on the teams app. I think we should restore these, and additionally link to the teams app from the sidebar of the homepage or something.

**Comment by nanoparsec** [comment]
<3

2014-07-11 17:32 GMT+02:00 Sven Fuchs notifications@github.com:

> [image: :+1:]
> 
> We had a link "Teams ->" in the top menu on the main page, which was
> removed earlier this year. And we had a link "Home ->" in the top menu on
> the teams app. I think we should restore these, and additionally link to
> the teams app from the sidebar of the homepage or something.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/summer-of-code/issues/227#issuecomment-48745234
> .

## 

_--------------_
_nerdbabe_

_Personal Contact Information_
_Email: mail@nerdbabe.de mail@nerdbabe.de_
_Website: nerdbabe.de http://nerdbabe.de_
_Twitter: *nerdbabe
https://mail.google.com/mail/ca/u/0/https//:twitter.com/nerdbabe
*Github:_ NerdBabe https://github.com/NerdBabe

**Comment by svenfuchs** [comment]
added the link back in on the homepage and teams app https://github.com/rails-girls-summer-of-code/summer-of-code/commit/ce2d3d2c80d4cb790ebd92476613054d7e3308a6 the teams app currently runs on travis ci and hopefully deploys to heroku then

**Comment by berlintam** [comment]
wow, so quick! awesome! :+1:
