### ISSUE TITLE
css code visible on coaching companies page

### ISSUE THREAD

**Issue by berlintam** [rails-girls-summer-of-code/summer-of-code-2014#232]
There's some wonky css on the [coaching companies](http://railsgirlssummerofcode.org/guide/coaching-company/) page:

![screen shot 2014-07-27 at 12 15 42](https://cloud.githubusercontent.com/assets/4237285/3713630/13f76d04-1579-11e4-9cf3-266406491719.png)

I tried to fix it myself but I'm not sure how to get the site up and running locally. Perhaps the readme can also be expanded so others can easily contribute.

**Comment by carpodaster** [comment]
I cannot reproduce this, looks alright here. My guess is that the async twitter js didn't fire for some reason. Is this still an issue on your end?

**Comment by berlintam** [comment]
it's fine now! weird....
