### ISSUE TITLE
Relaxing Day Off - Ideas & Inspiration

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/summer-of-code-2014#238]
On Aug 28th we'll have a house boat party, powered by [Applift](http://www.applift.com). Unfortunately, this is bound to Berlin and teletransportation is not yet reality. For this reason, we want to **nudge aaaall the students to take a day off and deliberately enjoy some non-coding, relaxing activity**.

To get some inspiration, here's our question to you - coaches, supervisors, mentors, and organizers:
**\+ What do you do to relax in stressful times?**
**\+ _alternatively_: What was your last or most favorite non-coding activity?**
(conferences, user groups, etc. are excluded!)

**Comment by alicetragedy** [comment]
Thank you for getting the ball rolling, @katrin-k!

I'll start by listing two of the things that really help me unwind.
The first is **baking**. I really enjoy the creative part of it (changing ingredients, figuring out what to do, decorating the cupcakes) and I like that it can be done alone or with someone else. I enjoy being able to listen to music while I bake, too - and of course, at the end you have a finished "product" you can admire (and eat!)
The second is **Taekwondo**. I used to go running a lot, but unfortunately in my area there are no awesome parks where I can do so; a dojang recently opened on my street, and I thought I would give it a try. Physical activity definitely helps to balance out all the hours spent in front of the computer, and Taekwondo has a very great set of values which anyone can learn from and apply in other areas in their life.

**Comment by carpodaster** [comment]
Our Dev-team went on an all-day **canoe trip** only recently and that was loads of fun! :boat: :sunglasses:  ([proof](http://devnull.absolventa.de/2014/08/06/ruby-on-waves/))

**Comment by anikalindtner** [comment]
- reading an acutal book or -even better sometimes - going into a magazines shop, buy ALL my favorite magazines and spend the day reading somewhere outside or snuggled up on the couch
- drawing something or writing down the latest ideas for blog posts/articles I had
- but the most relaxing to me is to do something totally different than what I do all day: sitting in front of the computer. So going to play volleyball with my family, (table) tennis, frisbee, going for a canoe trip, a swim, a bike trip, a yoga/meditation class or a run in a park always does the trick. 
  Studies show that just "hanging around" and doing nothing or only watching tv won't let you feel relaxed. Your brain wants to do things and experience stuff. So even if you really feel like slumbing away on the couch: get off your b*tt and go outside! what i can imagine would be a great idea is a media-free day. This works wonderf for me. Leave your laptop and phone at home and just head out.

**Comment by sareg0** [comment]
@katrin-k can we close this issue now?

**Comment by katrin-k** [comment]
yeah, i suppose so.
