### ISSUE TITLE
Pic wrongly labeled as Susanne...

### ISSUE THREAD

**Issue by berlintam** [rails-girls-summer-of-code/summer-of-code-2014#240]
The top-left pic in this blogpost:
http://railsgirlssummerofcode.org/blog/2014-07-29-talk-tips/

is labeled as Susanne Dewein... however... it is Steve Klabnik.

**Comment by FrauBienenstich** [comment]
bahaha...amazing! i feel honoured!
i am sure I can somehow dig up a real picture of me giving my talk in Israel if you want.

**Comment by carpodaster** [comment]
I think it's just the photo _credits_, no?

**Comment by FrauBienenstich** [comment]
I didn't read it that way, since it also says it's taken from my blog, which is supposed to be the credits I guess.

**Comment by katrin-k** [comment]
upsi. susanne, indeed, i took this pic from your blog and simply assumed it was you :D. sorry!

**Comment by FrauBienenstich** [comment]
no problem ;)
let me know if you need a new picture...

**Comment by katrin-k** [comment]
yeah, that'd be very good :). idea of the collage is to show rg-people in talk situations. 

if you could send it to katrin.kampfrath at railsgirlssummerofcode org… cheers!
