### ISSUE TITLE
Berlin group taxis 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#249]
Whee! Our boat trip starts tomorrow 3:45 PM. To make sure, everybody gets there, let's collaborate here.
#### Please comment, if you need to be picked up, or not.

if yes, please comment where you live (district)/ where would be a good district for you to meet other people going to the boat (Telegrafenweg 21 13599 Berlin-Spandau). Please paste the nearest U/S-station as well. 

Let's get this organized! <3

---

_I'm collecting all the answers here:_
#### Friedrichshain: 5
- _Anika, Magda, Susanne, (Sven), Bettina_
#### Kreuzberg: 6
- _Ute, Ernest, Jan, Brigitte, Sarah G., Lena_
#### Friedenau/Steglitz: 2
- _Arne, Laura_
#### Mitte: 5
- _Erik, Katrin, Lisa, Kathi_

---
- [x] Ute 
- [x] Magdalena 
- [x] Katrin 
- [x] Gosia 
- [x] Arne 
- [x] Jan
- [x] Ernesto 
- [x] Lena 
- [x] Susanne 
- [x] Bettina 
- [x] Brigitte 
- [x] Kathi 
- [ ] Michelle 
- [x] Erik 
- [x] Laura 
- [x] Sarah G.
- [x] Lisa +1

**Comment by nanoparsec** [comment]
Magda&I are in Kreuzberg near Görli/Schönleinstr. at Umspannwerk.

**Comment by anikalindtner** [comment]
I'm at Friedrichshain near Frankfurter Tor.

**Comment by plexus** [comment]
I'm fine with traveling there myself. I live in Friedenau (Schöneberg), should take about 45 min in total (https://goo.gl/maps/WAWFf). Or can meet anywhere south or west of the center :)

**Comment by FrauBienenstich** [comment]
I am working at Ubahn Warschauer Straße!

**Comment by anikalindtner** [comment]
@plexus can you name a s/u station which would be close-ish? I think there are some other people living in your corner..:)

**Comment by plexus** [comment]
Friedrich-Wilhelm-Platz is closest. bigger stations would be Rathaus Steglitz or Berliner Straße

**Comment by gosiaciesla** [comment]
Oh hai,

I'll be waiting for you in Spandau.

**Comment by emig** [comment]
Hi, from Umspanwerk, like Ute(NerdBabe) and Magda

**Comment by lauralindal** [comment]
ill be in dahlem, so rathaus steglitz would work nicely for me :)

**Comment by anikalindtner** [comment]
@lauralindal cool! i didn't know the names and email addresses from your learn group people.. could you forward this to them?

**Comment by katrin-k** [comment]
i work near rosenthaler platz (u8), but am happy to go somewhere closer to the others.

**Comment by lauralindal** [comment]
done, they should post here soon :)

**Comment by anikalindtner** [comment]
@lauralindal \o/

**Comment by schultyy** [comment]
Hi, also from umspannwerk as ernesto (emig), ute(nerdbabe) and magda

**Comment by kat-crumbs** [comment]
I'll be somewhere around Mitte. 

It would be interesting to know where the boat trip ends, because then I would leave my bike there....

**Comment by anikalindtner** [comment]
@kat-crumbs i'd think they take us back, no? i'll ask! :)

**Comment by BriocheBerlin** [comment]
I'll be in Neukölln but could go to Umspannwerk, too.

**Comment by BriocheBerlin** [comment]
Ehm, I am Brigitte...

**Comment by madziaf** [comment]
@anikalindtner -  i'll go from Friedrichshain, not Kreuzber
Frankfurter Tor works perfect for me

**Comment by anikalindtner** [comment]
@madziaf ok, i changed it <3

**Comment by anikalindtner** [comment]
@kat-crumbs so if you are taking your bike, then you don't need a taxi, right? or am i reading this wrong?
Also: yes, we are going to end up there, where we started. i just got the answer.

**Comment by sferik** [comment]
I will be coming from SoundCloud HQ in Mitte (Rheinsberger Straße 76/77). Anything around there works for me…or I could take me bike directly to Spandau.

**Comment by anikalindtner** [comment]
hahaha, i just googled "houseboat". do you all think we'll have this one? :D 

![](http://www.tourindiakerala.com/images/houseboat1.jpg)

**Comment by kilaulena** [comment]
Me also Umspannwerk/Schönleinstr!

**Comment by kat-crumbs** [comment]
@anikalindtner No, I won't go there by bike, Spandau is very far ;) I'd like to leave my bike somewhere around Stadtmitte or Alexanderplatz, ideally exactly on the spot where we will arrive with the boat in the evening. Do you know yet where the journey will end?

**Comment by anikalindtner** [comment]
@kat-crumbs yes, it will end, where we begin: Telegrafenweg 21 13599 Berlin-Spandau. that's why i was so surprised, you wanna take your bike there ;)

**Comment by sarahkami** [comment]
Hey, I'm a group Member of Laura's group.
I'm from Reinickendorf (Residenzstr)
Everything on U8 would be possible Gesundbrunnen? Alexanderplatz? Hermannplatz? Osloer Str?
Do you know when the boat trip will be finished?

**Comment by anikalindtner** [comment]
Hej @sarahganter, the trip will be about 3 hours and we have a BBQ afterwards for everyone <3
Ok, i've put you in the schönleinstr/umspannwerk group :)

**Comment by anikalindtner** [comment]
@NerdBabe could you be the head of the kreuzberg group and propose a pick up point? you then can just call a cab company to pick you all up. if i counted correctly, you'll be 6 people (if @SarahGanter is able to also join). Someone of you then has to pay, but we'll get the money back from Applift. Do you think you can manage that? Would be amazing! 

Since it takes about 45 min, I'd suggest calling a cab for 3 PM latest. WDYT?

**Comment by anikalindtner** [comment]
Another scenario: @SarahGanter and @katrin-k (both u8) could come to alexanderplatz and the cab from Friedrichshain could pick you up. What ever works for you two? also @sferik can join alexanderplatz maybe?

**Comment by sarahkami** [comment]
Both works for me, i just need a specific place to meet, as i don't know anyone and don't want to get in the wrong cab^^

**Comment by anikalindtner** [comment]
@SarahGanter hahaha yeah that would be a shame :D cool, that both scenarios work for you. let's see which group needs a person more in the end. i'll send out final infos with meeting places and telefon numbers latest tomorrow.

**Comment by BriocheBerlin** [comment]
@sferik wants to know if he can bring his bike on board.

**Comment by anikalindtner** [comment]
@sferik @BriocheBerlin i'd think so. but why? we are coming back to where we started.. or is it a super expensive bike that can't be left alone?

**Comment by nanoparsec** [comment]
Yes, sure, I can do that.
So I would say, lets meet at the main entrance of Umspannwerk at 14:45. 
For those who don't know anyone: I am the one with purple hair. You will see me :)
In case of emergencies: 0163/2558242 

@anikalindtner will we get the money back after the taxiride?

**Comment by anikalindtner** [comment]
@NerdBabe awesome! the money will be paid by applift. I'd think they can give it to you in cash afterwards. If not, I can do that and they will pay me back later.

**Comment by nanoparsec** [comment]
@anikalindtner coolio :)

**Comment by anikalindtner** [comment]
@plexus and @lauralindal can you form a group as well? i don't know if we'll have someone join your group still, but can somebody of you two be the "head" of your group and make sure, you meet at the same place and order a taxi? And pay for it.. you'll get the money back of course. Just keep (important!) the receipt :)

**Comment by anikalindtner** [comment]
@NerdBabe oh, very important: keep the receipt! :)

**Comment by BriocheBerlin** [comment]
Michelle wasn't included in the email, I just forwarded it to her.... I expect she'll be in Przlberg.

**Comment by anikalindtner** [comment]
@BriocheBerlin i already sent her the email :)

**Comment by lislis** [comment]
Hey, I would also prefer somewhere in Mitte.

**Comment by sferik** [comment]
I can go to Alexanderpltaz, if that would make things more convenient. I think @miveronese will also be coming from Mitte, near SoundCloud HQ, since she lives around there.

**Comment by sferik** [comment]
Also, when will the BBQ begin and where will it be hosted? @starkcoffee is not able to ride the boat but she would like to join later, for the BBQ.

**Comment by thatbettina** [comment]
@anikalindtner Does the F'hain cab have room to pick me up at Ostbahnhof? Tell me when I have to be outside it.

**Comment by anikalindtner** [comment]
@sferik and @thatbettina: I just got the info that the BBQ will be on the boat, during the trip. So no afterwards... sorry, I totally misunderstood that.

**Comment by anikalindtner** [comment]
@thatbettina and sure, the friedrichshain cab can pick you up at Ostbahnhof!

**Comment by thatbettina** [comment]
Great, just let me know when and I'll be there :)

On Wed, Aug 27, 2014 at 9:46 PM, Anika notifications@github.com wrote:

> @thatbettina https://github.com/thatbettina and sure, the
> friedrichshain cab can pick you up at Ostbahnhof!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/summer-of-code/issues/249#issuecomment-53629534
> .

## 

Bettina Shzu-Juraschek
Fuldastraße 19-20
12045 Berlin

+49 (0)163 164 7045
bettina.shzu@gmail.com

**Comment by lauralindal** [comment]
i think @plexus and i decided to just take the ubahn. probably makes more sense b/c of traffic and since we're just two people :)

**Comment by anikalindtner** [comment]
for the Mitte-Group, @lislis will be 'head of group'. @lislis can you give a meeting point where everyone  (@sferik, @katrin-k, @miveronese ) should meet you? then you can call a group taxi and give them the address and the money (please remember the receipt <3).

**Comment by anikalindtner** [comment]
@lauralindal auch fein :) cool, see you there! if there are any problems, ping me or sarah from applift. I'll send all the important numbers around in a separate email.

**Comment by anikalindtner** [comment]
@madziaf @FrauBienenstich @thatbettina: welcome to the Friedrichshain group ;)

Let's meet at Grünberger Str./Warschauer Str: at 2:45 PM

![Uploading Screen Shot 2014-08-27 at 21.58.19.png . . .]()

so, @thatbettina can you come to that corner? else, you'd probably have to be outside of ostbahnhof the same time and wait for us.

**Comment by thatbettina** [comment]
2:45pm outside Ostbahnhof for me please :)

On Wed, Aug 27, 2014 at 9:56 PM, Anika notifications@github.com wrote:

> @madziaf https://github.com/madziaf @FrauBienenstich
> https://github.com/FrauBienenstich @thatbettina
> https://github.com/thatbettina: welcome to the Friedrichshain group ;)
> 
> Let's meet at Grünberger Str./Warschauer Str: at 2:45 PM
> 
> [image: screen shot 2014-08-27 at 21 54 41]
> https://cloud.githubusercontent.com/assets/1711357/4066450/024cbc1c-2e24-11e4-8b54-cef54109f2c0.png
> 
> so, @thatbettina https://github.com/thatbettina can you come to that
> corner? else, you'd probably have to be outside of ostbahnhof the same time
> and wait for us.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/summer-of-code/issues/249#issuecomment-53630954
> .

## 

Bettina Shzu-Juraschek
Fuldastraße 19-20
12045 Berlin

+49 (0)163 164 7045
bettina.shzu@gmail.com

**Comment by anikalindtner** [comment]
@thatbettina ok :) 

see you then here:

![screen shot 2014-08-27 at 22 00 26](https://cloud.githubusercontent.com/assets/1711357/4066546/cdeb022a-2e24-11e4-8b22-ebb9818e9ade.png)

**Comment by anikalindtner** [comment]
@SarahGanter you'll be in the Kreuzberg group then. can you give me your email address, so i can send you the next email as well?

**Comment by kat-crumbs** [comment]
@anikalindtner sorry if there are still misunderstandings. I need a cab, too, as I won't take the bike to Spandau. May I join the Mitte group (supposedly starting from Alexanderplatz)?

**Comment by sarahkami** [comment]
yellow_daffodil@web.de

**Comment by lislis** [comment]
Team Mitte (@sferik @katrin-k @miveronese and @kat-crumbs ) are you ok with meeting here? http://www.openstreetmap.org/?mlat=52.52217&mlon=13.41293#map=18/52.52217/13.41293
15:00 sharp

**Comment by sferik** [comment]
@lislis :+1:

**Comment by anikalindtner** [comment]
@kat-crumbs wahh sorry, didn't mean to forget! yes, please do join the mitte group// cc @lislis

**Comment by katrin-k** [comment]
@lislis all great! 

michelle had to cancel. she got a last-minute note she'll have to work.

**Comment by lislis** [comment]
oh noes :( 
But that means we can take a normal taxi, right? I won't bring a +1 and then we're 4. Or am I missing something?

**Comment by katrin-k** [comment]
hmmm. right. or we join the fhain group (also 4).  afaik, a large taxi can hold up to 8 ppl.

**Comment by anikalindtner** [comment]
@lislis @katrin-k nah, you can just take a normal cab then. don't worry

**Comment by thatbettina** [comment]
Yes, see you there at 2:45pm.

On Wed, Aug 27, 2014 at 10:00 PM, Anika notifications@github.com wrote:

> @thatbettina https://github.com/thatbettina ok :)
> [image: screen shot 2014-08-27 at 21 59 46]
> https://cloud.githubusercontent.com/assets/1711357/4066537/bb30d164-2e24-11e4-8fbd-0c466b468852.png
> see you then here:
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-girls-summer-of-code/summer-of-code/issues/249#issuecomment-53631563
> .

## 

Bettina Shzu-Juraschek
Fuldastraße 19-20
12045 Berlin

+49 (0)163 164 7045
bettina.shzu@gmail.com

**Comment by anikalindtner** [comment]
@lislis die Edna vom Team speakerinnen kommt noch mit und ist dann bei eurer gruppe dabei! :)

**Comment by sferik** [comment]
Unfortunately, I suffered an injury playing football last night and won't be able to make it today. :(

Alexanderplatz group: please don't wait for me.

**Comment by sferik** [comment]
I was just dismissed from the hospital and am riding in a cab toward Spandau. I should arrive in approximately 30 minutes. Would it be possible for you to hold the boat until 4:15?

**Comment by sareg0** [comment]
@anikalindtner I am going to close this up.
