### ISSUE TITLE
RGSoC Awesome 2014 Mix Tape

### ISSUE THREAD

**Issue by sareg0** [rails-girls-summer-of-code/summer-of-code-2014#257]
Hi Everyone,

Just like last year, we're going to add a song each to an awesome playlist on Soundcloud

https://soundcloud.com/railsgirlssummerofcode/sets/rails-girls-summer-of-code

The only thing you have to keep in mind, is that the song comes from the original artist (if it is the original), and if it is coming from someone else, that it is a remix. 

Viel spaß!! 

Let me know if you need help.

**Comment by alicetragedy** [comment]
awesome! are there any other guidelines other than the copyright infringement issue? Also, do we have to have access to the Soundcloud account to add a song, and if yes, can you see who added which song or do we have to mention it here? (Or does it not matter hihi)

**Comment by sareg0** [comment]
Apart from copyright, nothing bigoted, racist, or sexist. I know there will be some rap songs that could cross that line, but you guys can use your judgement, and we trust you. I quite like Hip hop, but went for Sia cause she's pretty awesome. Just anything you feel represents your summer. Fevered dubstep? Chill folk? Whatever you feel. Doesn't have to be as mainstream as my choice ;)

I have made the mixtape a public playlist, so you can all add from your own accounts. Hopefully we will be able to see who has contributed that way :)

Having said that, if it doesn't have ur name attached to it when you add it to the list, then just leave a comment here to say you selected your song. Once orga and supervisors and everyone have contributed then we will open it up to students.

**Comment by FloorD** [comment]
Choosing one song is the hardest thing ever.

**Comment by FloorD** [comment]
no.idea. how to add a song, but I would love to see this one in there: https://soundcloud.com/future-islands/seasons-waiting-on-you

**Comment by sareg0** [comment]
Great! Added. If everyone else could do theirs in the next day or two, and we can then tweet it out. I can add it for you too if you can't figure it out, cause it seems to be a bit tricky. Just post the link to the track you want on the mixtape here.

**Comment by carpodaster** [comment]
Don't know how to add it to the list, either. In fact, I don't know how to use Soundcloud at all :wink:  And most songs aren't available, so I'll throw in this one: https://soundcloud.com/iscintilla/omen

**Comment by alicetragedy** [comment]
I also have the same problem, I looked in the help area but there was no information about adding a song to a public playlist, only to one's own :(
Anyway I'm gonna go with Touché Amoré cover of "Available" (originally by the National). The song was recorded for a compilation and posted on SoundCloud by the record label, so I'm pretty sure that all rights were cleared. 
Here is a link: https://soundcloud.com/nosleeprecords/touche-amore-available

**Comment by cypher** [comment]
Same here, so here's a link: https://soundcloud.com/futurelights-1/lust-1 (the artists themselves posted it to Soundcloud)

**Comment by FrauBienenstich** [comment]
there you go! https://soundcloud.com/flightfacilities/flight-facilities-clair-de-1

**Comment by sareg0** [comment]
I am going to close this issue now, but if anyone wants more songs added who hasn't yet contributed, please just let us know via twitter, email or slack
