### ISSUE TITLE
Goody Packs Blog Post

### ISSUE THREAD

**Issue by sareg0** [rails-girls-summer-of-code/summer-of-code-2014#264]
title: For The Goodness of Swag

The Rails Girls Summer of Code cohort for 2014 have almost made it to the finish line of the program.
Some who finished early, have now moved on, and some are battling through the final days to achieve their project goals.

Before the gray days (or the bright, sunny days depending on your hemisphere) of post SoC were upon us, we had to remind participants just how much we love them,
with a little care package.

To the surprise of, hopefully, most of our participants they would have received a big yellow box in the mail, filled with all sorts of delightful swag,
from our sponsors. From t-shirts, to stickers to pens, to notepads to ballons - the packages were chock full.
Unfortunately, unicorn eggs are strictly prohibited from being posted internationally, but we will work on that for next year.

![A BUNCH OF SWAG](/img/goodypack2014.jpg)
### Why We Like To Send Goody Bags

In and of themselves, the monetary value of the swag we send is pretty minimal. But the monetary value is not what counts.

Our goody packs are an opportunity for us to remind teams that someone is thinking of them, and sending them love from afar.

We hand packed every package so, if you happen to be a team that did not receive your swag package, please just drop us a line.... After all mistakes can happen, and sometimes they can take a while to get delivered.

It's a chance for sponsors to make themselves present in the lives of the participants. Sure, it's only a sticker or notepad to an outsider, but it's intrinsic value to the person who receives it is priceless.

Getting that bright yellow (DeutschePost) box in the mail and getting to crack it open, is like being a kid on christmas morning; likely you have an idea what's going to be inside, but it's still fun on a bun.

The stickers recipients put on their computers, and around their houses remind them of their time in the program, and who made it possible; our sponsors, and volunteers.

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p>Thanks for our gifts !!!! 🙌😁🙋 <a href="https://twitter.com/RailsGirlsSoC">@RailsGirlsSoC</a> <a href="https://twitter.com/github">@github</a> <a href="https://twitter.com/site5">@site5</a> <a href="https://twitter.com/wooga">@wooga</a> <a href="https://twitter.com/planio">@planio</a> <a href="https://twitter.com/Groupon">@Groupon</a> <a href="https://twitter.com/cloudcontrolled">@cloudcontrolled</a> <a href="https://twitter.com/keen_io">@keen_io</a> 👏👏 <a href="http://t.co/DcLIhdCjIX">pic.twitter.com/DcLIhdCjIX</a></p>&mdash; ARIATeam (@GirlsARIA) <a href="https://twitter.com/GirlsARIA/status/515145367571431424">September 25, 2014</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p>Thanks for the gifts!!! <a href="https://twitter.com/RailsGirlsSoC">@RailsGirlsSoC</a>   😊 🎁</p>&mdash; Team Migraine (@migraine_io) <a href="https://twitter.com/migraine_io/status/515205793617301504">September 25, 2014</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p>I&#39;m all good for t-shirts! Thanks <a href="https://twitter.com/RailsGirlsSoC">@RailsGirlsSoC</a> <a href="https://twitter.com/carpgezwitscher">@carpgezwitscher</a> <a href="http://t.co/1l72NvV6uC">pic.twitter.com/1l72NvV6uC</a></p>&mdash; Tracy Mu Sung (@TracyMuSung) <a href="https://twitter.com/TracyMuSung/status/515429230755074048">September 26, 2014</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

So, again, why? Because it's nice, it's fun, and most of all everyone likes getting a present.
What makes Rails Girls Summer of Code special is the spirit behind the program.
Open Source is about community and contributing to make things better, and we try to remind participants of that every step of the way.

Thanks so much to our sponsors for sending all of the swag!

Stay tuned to the blog over the next few days as we close up the program for 2014.
We'll be posting the last remaining Team blog posts, and thanking our sponsors for their generous contributions this year.

WARNING: Gratuitious selfies may be involved.

**Comment by carpodaster** [comment]
>  filled with all sorts of delightful swag, from our sponsors. 

Is the last comma correct?

> but it's intrinsic value to the person who receives it is priceless.

it's -> its

> Thanks so much to our sponsors for sending all of the swag!

Link **sponsors** to our sponsors page?

**Comment by cypher** [comment]
> > filled with all sorts of delightful swag, from our sponsors.
> 
> Is the last comma correct?

Yep. You can completely remove the "filled with all sorts of delightful swag" part of the sentence, and it still remains a valid and sensible sentence.

**Comment by sareg0** [comment]
if you removed the comma it would also be fine, either way reads fine. Technically I should remove the comma because if you removed that part of the sentence it would read.

"most of our participants they would have received a big yellow box in the mail from our sponsors."

That isn't exactly true, so removing the comma would makes sure it read that the swag is from the sponsors not necessarily the package... But very good point you guys, your grammar is better than mine :)

**Comment by sareg0** [comment]
@carpodaster I added the link to the sponsors page

**Comment by sareg0** [comment]
published, closing.
