### ISSUE TITLE
Donations table not showing on campaign page

### ISSUE THREAD

**Issue by ellenkoenig** [rails-girls-summer-of-code/summer-of-code-2014#28]
Browser: Firefox, Ubuntu
Checking the source code, I find that the tbody-Tags of the table where the donations by supporters should be displayed are empty.

**Comment by svenfuchs** [comment]
Thanks for reporting, @EllenKoenig 

Hmmm, yeah, the table should be populated from some json that we get through javascript from remote, which is why the tbody is empty.

Could you provide more information about this? Are there any javascript errors in the console/log? Any assets not being loaded?

**Comment by ellenkoenig** [comment]
@svenfuchs Yes, there is a JS error on the console:

donations.js (Zeile 132)
TypeError: this.data.package is undefined
var text = this.data["package"].camelize();

**Comment by svenfuchs** [comment]
Hmmm, @EllenKoenig that is super odd :)

Could you check for the donations.json payload it loads from campaign.railsgirlssummerofcode.org/donations and see what's in there? You'd want to use firebug or something like that for it so you can inspect the payload that is actually being loaded and used in JS.

It should have an array of hashes where each hash has a key "package" like this:

![image](https://f.cloud.github.com/assets/2208/572588/67717b20-c79e-11e2-8b17-e077bae352ae.png)

**Comment by ellenkoenig** [comment]
The JSON object looks fine as far as I can tell.

**Comment by PragTob** [comment]
What's your Firefox version @EllenKoenig ? Everything fine over here on FF 21 and Linux.

**Comment by carpodaster** [comment]
I can confirm that it's not showing on FF 20.0 on Mac. Did an update and … voilá … it's indeed working w/ v21.0

**Comment by ellenkoenig** [comment]
As @carpodaster described: A Firefox update solved the problem. Just for the record: I noticed it is also not working on my slightly outdated iOS safari, however, I don't think this is necessary to fix.

**Comment by carlad** [comment]
Gonna close this one as noone can reproduce it. If it's still an issue then we can re-open.
