### ISSUE TITLE
Donate with Paypal

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/summer-of-code-2014#33]
Hi. Do we want to add a Paypal donate button? https://www.paypal.com/en/cgi-bin/webscr?cmd=_donate-intro-outside  It looks dead ugly, but for people unwilling to supply their credit card info, that might a good alternative.

/discuss! :)

**Comment by svenfuchs** [comment]
The issue with paypal is that campaigns like ours are likely to be blocked, so the money is lost ... based on reported experiences made by others.

**Comment by carpodaster** [comment]
Fair enough – makes sense! -> close.
