### ISSUE TITLE
Add info about payment security @ Donation window

### ISSUE THREAD

**Issue by ialja** [rails-girls-summer-of-code/summer-of-code-2014#35]
Love the project and was of course very keen on donating, but I've never seen the Stripe Checkout overlay before, so I was a bit hesitant about leaving my credit card info on the page. That's why I'd suggest adding a "Is my payment secure?" link right below the Donate button that would lead either to a page explaining Stripe security or maybe just a mouse over box that explains what system is being used.

**Comment by svenfuchs** [comment]
I agree, thanks for the headsup @ialja!

Can someone take care of this?

**Comment by unicornzero** [comment]
I see that the /campaign page currently includes a line of text under the donation button stating "Secure Payments by Stripe Checkout". Do we want to leave this as-is, or perhaps also include a link to https://stripe.com/help/security ?

**Comment by svenfuchs** [comment]
Hey @unicornzero, thanks for the hint!

We've choosen to link to that stripe blog post https://stripe.com/blog/stripe-checkout because it shows the same UI overlay that confused people, mostly because it looked unfamiliar.

I'd personally keep it like this, wdyt.

**Comment by unicornzero** [comment]
@svenfuchs 
Sounds good to me! Does that mean this issue can be closed?
Cheers!
Rylee

**Comment by svenfuchs** [comment]
jep, let's close it then. thanks :)
