### ISSUE TITLE
Website landing page

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#4]
Re https://github.com/RailsGirlsBerlin/summer-of-code/wiki/Website-landing-page----first-version-%28Projects-focus%29

@EllenKoenig is it ok for you to discuss the landing page over here in the issues? I have some comments but I don't want to simply change your text. Please close this issue if you want people to comment by directly editing the wiki page.

```
RailsGirls Summer of Code wants to help engage Open Source community newbies in projects
```

I think it should mention that we're targeting specifically women who are RailsGirls, RailsBridge, ... students, not sure what's the best word here. Maybe just say "RailsGirls students" and then add a comment or even footnote somewhere, saying that people from other learning workshops are welcome, too? Dunno :/

Afaik the term "newbie" sometimes has a negative connotation. "Newcomer" is better.

How about

"RailsGirls Summer of Code helps RailsGirls students get into Open Source."

```
... but rather cool small projects that are perfect for involving newbies.
```

Don't need to be small :) Also, maybe put the emphasis on learning, "getting in touch", "getting into it" ...

How about

"... but rather further expanding their knowledge and skills by contributing to a great Open Source project"

And maybe flip the negative/first and positive/second statement around? As in

"Unlike those programs RgSoC is about [learning](rather than [working on sophisticated code])"

?

After a short discussion on the #rubinius irc channel yesterday I'm also thinking more about what a good description of what an "ideal" project could be. I think we'd want to put more emphasis on the fact that the coach will most probably need to guide the student towards the programming goal. The whole thing seems more and more like a mentored/coached learning experience to me. The project description should include something like that. The benefit for the project would rather be the fact that they are able to participate in something awesome like this rather than getting some real work done they've always wanted to see. Dunno. Gotta think more about this.

**Comment by ellenkoenig** [comment]
@svenfuchs Good points, I will incorporate them later. When you come up with a better description of the ideal project, let me know.

However, I disagree with the notion that the projects should only be "something awesome"; and not something that needs to be done. I think for everybody involved (student, project, coaches) it will be much more motivating to get some real work done as well. Three months imho is too a long period to spend just on "educational and fun busywork".

**Comment by svenfuchs** [comment]
@EllenKoenig Hmmm, I think we're mostly on the same page with that, just looking at it from different perspectives. If you ask Rubinius what's on their todo-lists then that's all pretty sophisticated stuff. So in that case it probably might make sense to come up with a goal that previously hasn't been on the list or would have been managed in a different way.

I assume that with "real work" you're more generally aiming at stuff that has a "real impact" on the OSS project, right? I agree that's something we should aim at.

Still, otoh, since this description should guide potential project owners we'd also need to explain to them that the main objective is an educational one ... and coming up with good project goals, guiding the student through all of this and eventually have the student make a meaningful, "real" contribution is a mean to that end.

wdyt?

**Comment by svenfuchs** [comment]
@EllenKoenig I've added an updated version to the wikipage https://github.com/RailsGirlsBerlin/summer-of-code/wiki/Website-landing-page----first-version-(Projects-focus)

WDYT?

**Comment by ellenkoenig** [comment]
@svenfuchs :+1:  I like ;)

**Comment by svenfuchs** [comment]
Hey @EllenKoenig I was looking for the work you and @txus have done yesterday, but I can't find it on the wiki. Where do I have to look at?

**Comment by ellenkoenig** [comment]
@svenfuchs https://github.com/RailsGirlsBerlin/summer-of-code/wiki/Projects 

The first section is our proposed text for the landing page, the second one for the projects page.

**Comment by svenfuchs** [comment]
ah, perfect. /me blind. thanks! :)

**Comment by svenfuchs** [comment]
closing this since we're good to go here
