### ISSUE TITLE
javascript error on /campaign: donations are not shown any more

### ISSUE THREAD

**Issue by jmentz** [rails-girls-summer-of-code/summer-of-code-2014#46]
There is a javascript execution error in donations.js on line 68, if you open http://railsgirlssummerofcode.org/campaign in the current Firefox or Chrome browser:

```
Uncaught TypeError: Object #<Object> has no method 'sortByAmount'
```

It seems the problem was introduced by commit 6e9bea4d9f2b62939bca5d2762a30ae68cdb7e2e (the javascript method did not exist before).

I unfortunately can't fix it right now myself, because i am at work.

![screen shot 2013-06-03 at 6 10 56 pm](https://f.cloud.github.com/assets/334336/600480/a6374d84-cc68-11e2-8d0a-8286c95e8e27.png)
![screen shot 2013-06-03 at 6 10 49 pm](https://f.cloud.github.com/assets/334336/600482/ac1b6cb2-cc68-11e2-94cd-963e98a92b7f.png)

**Comment by PragTob** [comment]
Weird works for me with both browsers.

**Comment by jmentz** [comment]
Yes, because the code that caused the error has been commented out. :)

**Comment by PragTob** [comment]
argh update problem on my side... thought I answered like 5 mins after you posted the problem.

**Comment by svenfuchs** [comment]
yeah, sorry about that. accidentally committed an unfinished piece of code :/
