### ISSUE TITLE
Improve placement and size of the video on the start page

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#47]
It's a great start, but I think it should be bigger and maybe placed more prominently.

@ josepjaume @lislis anyone able to help with this short term?

**Comment by lislis** [comment]
Hmm maybe we could add another 'slide' to the front page, together with another image. 
So when you scroll down you get:
- image
- video
- image
- text
- image
- text
- footer

or would this be too long?

**Comment by svenfuchs** [comment]
Would we need that extra image between the video and the "Women go open source" heading?

I'd probably try these first:
- place it in the "women go open source" section, also really big, above the headline
- place the video on the first image section, and make it really big
- same as before but make it have the same image background, but with a semi transparent color overlay, hmmm not sure how to describe that

:)

**Comment by svenfuchs** [comment]
Hmmm, not really perfect. But maybe a start? Move the headline above the video and make it white? I'd need to play with this more, but unfortunately I have to go and work on sponsor emails more :/

![skitched-20130604-114317](https://f.cloud.github.com/assets/2208/604649/89b7fa1c-ccfb-11e2-9c76-5258ccf61cf9.jpg)

**Comment by lislis** [comment]
I tried your first suggestion, which fits very good into the whole page (imo).
![videoplacement](https://f.cloud.github.com/assets/1006478/604674/528e964e-ccfc-11e2-9a74-0e8afad6f823.png)

**Comment by svenfuchs** [comment]
Yeah, that's not too bad!

Hmmm could you try moving the headline above the video, align the video to the left and make it have the same amount of padding?

**Comment by lislis** [comment]
Hmm like this?
![videoplacement2](https://f.cloud.github.com/assets/1006478/604809/2179535a-cd01-11e2-814f-c1c971612fdb.png)
Then we could also take the scribble back in.

**Comment by svenfuchs** [comment]
Yeah! I think that's much better than what we have now. Let's use it?

**Comment by jmentz** [comment]
Yes, I like it.
I would just give the scribble a bit more margin-top, so that it's aligned next to the video.

**Comment by lislis** [comment]
Commit: 555ab1ea713aa8bd8f208b792db0427395c5f077
What do you think?

**Comment by jmentz** [comment]
Very nice! :+1:

**Comment by svenfuchs** [comment]
@lislis :heart: :heart: :heart: !!!
