### ISSUE TITLE
Mockup with proposal 1 for website

### ISSUE THREAD

**Issue by carolinagc** [rails-girls-summer-of-code/summer-of-code-2014#5]
I had a couple of mockups with proposals for the website. First I will post proposal 1.
I hope that if there are any questions I'll be able to follow up, but since I'm abroad, time management is a bit difficult & different ;-)
file with proposal for download, since I didn't find how to uploada file associated to the issue

http://ubuntuone.com/4kxvNypzgPB39JlrMCX0GC [File URL updated]

pd: Is there a posibility to upload files to the issues?

**Comment by lislis** [comment]
I can't open the link without and account. But you can just add an image by clicking on the Edit in the upper rigth corner and choose an image.

**Comment by carolinagc** [comment]
Yes, sorry, I didn't make public the link, now it's changed and should be ok. It's a zip file with several images, that is why I didn't upload it directly in the issue.

**Comment by svenfuchs** [comment]
@carolinagc it still asks me to sign in?

**Comment by carolinagc** [comment]
Using the new link still asks you so?

http://ubuntuone.com/4kxvNypzgPB39JlrMCX0GC 

mmm strange ... without being logged in I can download it ...

**Comment by svenfuchs** [comment]
@carolinagc ah! no, that link works. i just haven't seen that link before? maybe i'm just confused ... :) thank you!

**Comment by carolinagc** [comment]
Well actually I changed the URL in the original post, so that it was not necessary to scroll down ;-) ... perhaps that is the confusing part :-/
