### ISSUE TITLE
Mockup with proposal 2 for website

### ISSUE THREAD

**Issue by carolinagc** [rails-girls-summer-of-code/summer-of-code-2014#6]
This is the second proposal and youcan download it at

http://ubuntuone.com/3cPQsCHybPwyvYSLsQzJyz [updated URL]

**Comment by svenfuchs** [comment]
@carolina sounds great, but it seems that ubuntu requires a login for this. is this on purpose?

**Comment by carolinagc** [comment]
Nop, not on purpose, just forgot to publish the URL, Now is updated, so it should be ok

**Comment by carolinagc** [comment]
The new URL that should enable you to download the file (also updated on the first post)
http://ubuntuone.com/3cPQsCHybPwyvYSLsQzJyz
