### ISSUE TITLE
Add a jekyll based blog?

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#63]
We're working on a blog post about the student selection. Since Henrietta is quite busy we were wondering if we should just add a jekyll based blog to our site?

Could someone look into this?

**Comment by PragTob** [comment]
Also here the link to [octopress](https://github.com/imathis/octopress)

**Comment by svenfuchs** [comment]
Done. Just using plain Jekyll for now.

Please help to improve this :)
