### ISSUE TITLE
Change images on Press page to thumbnails

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#64]
@anikalindtner will have more info :)

**Comment by PragTob** [comment]
On Twitter Alex mentioned that we might need more high res photos/logos for the press.

**Comment by anikalindtner** [comment]
argh, we do have the photos in high resolution. these are only previews. but we forgot to the link to the original size.
could somebody do it? if you click on "open pic in new tab", then you'll have the high res version..

**Comment by jmentz** [comment]
I linked the shown photos to their full-sized version.

As of now, the photos on the press page are no real thumbnails. They are the original photos and just downscaled by the browser. This makes the site slower to load and slower to scroll (at least on my ancient laptop).
The images seem to be stored in a github cloud, which i do not know how to access. If you could tell me how to access it or provide me smaller versions of the images, i can replace the images shown on the press page with the smaller versions.
