### ISSUE TITLE
Turn "Contact" into "About" and add team information

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#66]
We need a place to tell who's behind this, like a "Team" page.

Maybe we could just rename "Contact" to "About" and then have both sections on there.

**Comment by unicornzero** [comment]
Would this be a place to include information about program organizers?

**Comment by PragTob** [comment]
As far as I understand, yes :-)

**Comment by unicornzero** [comment]
I see some organizer information at http://teams.railsgirlssummerofcode.org/teams/12
Are we thinking of linking to that, including that info, or getting more than I currently see there?

**Comment by svenfuchs** [comment]
I was more thinking of a hand crafted page like http://railsgirlsberlin.de/about/organizers, but yeah, we could also just pull data from the teams application through ajax.

**Comment by fannivuniconnu** [comment]
We are actually  in the process in changing this as well btw, we'll just have handles and avatar (more detailed info will be to found in a blogpost from the one organizer)

---

**Comment by carlad** [comment]
Am wondering whether the "Student Registration" and "Project Registration" buttons should still be on this page?
Am happy to remove them if not.

**Comment by lislis** [comment]
Well, the contact page is now the about page, the current thread is referenced above. Close this one
