### ISSUE TITLE
Blog layout

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code-2014#69]
I applied the same same content width to the blog posts to improve readability.
Question is how to further work on the blog.
I think a an post overview in the sidebar would be great. 
Other suggestions?

**Comment by svenfuchs** [comment]
@lislis super, that's much better!

hmmm, maybe we could add a call to action to the sidebar, too. like "help us add another student and donate!" or something. maybe that could just be a box for now, with a link and another sentence?

**Comment by lislis** [comment]
That's a good idea. Unfortunately I won't come around to do it today. And for me it is always easier working after a design (otherwise it will look kinda horrible ;)), can you (or someone else) do a little sketch on it?

**Comment by svenfuchs** [comment]
btw @anikalindtner noticed that we also need to add a big phat rss button :)
