### ISSUE TITLE
Add "Teams" pages

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#70]
I think we should have a "Teams" page, that has an overview of all the teams, then link to another page per team, where each team gets to present their profiles and projects etc.

**Comment by unicornzero** [comment]
Is there content for this available yet? What might be included in the team profiles? Would this most likely be a list of student teams and/or something that teams could dynamically update? Do you think the page title of "Teams" or "Students" would be a good fit? :)

**Comment by svenfuchs** [comment]
Ah, yeah, we now have a full application for it, running at http://teams.railsgirlssummerofcode.org

:)

Closing this. Thanks!
