### ISSUE TITLE
add comments to blog

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#73]

**Comment by unicornzero** [comment]
Could this be broken into two issues? Seems it might be easier for someone to do one than the other/both?

**Comment by carlad** [comment]
good idea unicornzero. done.

**Comment by lislis** [comment]
Maybe we could implement Disqus http://disqus.com/
Implementation seems easy, maybe I can get into it soon.

**Comment by svenfuchs** [comment]
@lislis yep! 

there still is a commented disqus thingy in the blog post layout: https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/_layouts/post.html#L37

i guess you could just create an account using the summer-of-code@railsgirls.com email address or our twitter account

**Comment by lislis** [comment]
Nice! And done ;)
Commit 18cf92baeab19271ace4be5a6c2f78b0efdbd5d3

**Comment by anikalindtner** [comment]
whooha! awesome :)
