### ISSUE TITLE
fix scribble on "campaign" and "index" site

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#74]
it's not fully displayed (used chrome)

**Comment by anikalindtner** [comment]
huhu @lislis kannst du das machen? irgendwie scheint da was verrutscht zu sein 
![screen shot 2013-06-21 at 3 40 02 pm](https://f.cloud.github.com/assets/1711357/687328/1c2c48b0-da78-11e2-8b4c-645fd8f365a0.png)

**Comment by lislis** [comment]
Jup
Commit: 97e30a6b6eb148f85445052f686d96df409d42f7
