### ISSUE TITLE
add share-buttons to blog

### ISSUE THREAD

**Issue by carlad** [rails-girls-summer-of-code/summer-of-code-2014#76]

**Comment by lislis** [comment]
Which ones would you like to have? Twitter, FB, G+ ??

**Comment by carlad** [comment]
twitter is probs most good for tech crowd
fb might be wise in terms of reaching a broader (and female) audience.

**Comment by lislis** [comment]
So Twitter and FB it will be :)

**Comment by lislis** [comment]
Now appearing on the single blog posts, abc6d39d905ef186f9df4f4a3fe51f8b833a428d dcbbf2b0e4fc960dc65f4c602ce2c0cc421258e9 7a9e1c86420eb439667b119123e01e85921994eb

**Comment by svenfuchs** [comment]
\m/
