### ISSUE TITLE
add blogroll to blog-sidebar

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#79]
with links to team-blogs:
http://inchworms.net/blog/
http://highwaytorails.tumblr.com/
http://punchgirls.wordpress.com/
http://railsgrrls.tumblr.com/
http://newrosies.tumblr.com/
http://disaster-assistance.blogspot.co.at/
http://lipen.co/til/

(list not complete)

**Comment by PallaviTS** [comment]
This  list on which page ?
We want to add our blog :)

**Comment by svenfuchs** [comment]
Heya

I've added a sources resource to the teams app, so we could add this blogroll through an ajax request (and always have an up-to-date list of blogs)

http://teams.railsgirlssummerofcode.org/sources.json?kind=blog

@PallaviTS I guess it would make sense to just add it to the blog for now. Once implemented we might wanna display it on the homepage, too, which should get a makeover soon.

**Comment by svenfuchs** [comment]
Here we go:

![image](https://f.cloud.github.com/assets/2208/715358/76d0d732-df18-11e2-8665-ecb9282b92b3.png)
