### ISSUE TITLE
change the fav icon to the official Rails Girls Logo

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#88]

**Comment by lislis** [comment]
Done :)
commit : e7a16c724a363af366472679ef0a46ddcb33e43e

**Comment by svenfuchs** [comment]
Doesn't seem to pick it up for me?

![image](https://f.cloud.github.com/assets/2208/760868/d3328e18-e7b9-11e2-8a40-039390061789.png)

Btw, @lislis if you change things like this, or also stuff related to the top menu bar, could you do a related change on the teams app, too? :) 

https://github.com/rails-girls-summer-of-code/rgsoc-teams

**Comment by svenfuchs** [comment]
aah, i only just saw https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/24

thank you :)

**Comment by lislis** [comment]
I just noticed that I didn't put the new favicon into the teams app, just the logo. Is there some shortcut for implementing a favicon in an Rails app?

**Comment by svenfuchs** [comment]
unknown :/

**Comment by lislis** [comment]
hmm google/ stackoverflow says
 = favicon_link_tag "favicon.ico"
I coould just put it in the application.slim, right?
