### ISSUE TITLE
add #rgsoc twitterstream to blog sidebar

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#89]

**Comment by lislis** [comment]
Do you suggest two boxes, one with #rgsoc and one @railsgirlssoc ?

**Comment by anikalindtner** [comment]
yeah, that would be cool!

**Comment by lislis** [comment]
Is it still possible to donate? otherwise I would take out the 'help us' bit to make more room

**Comment by anikalindtner** [comment]
it's still possible, but you could push it down to have room for the twitter boxes?

**Comment by lislis** [comment]
Sure, I'll make it @Twitter, #Twitter, 'Help us', 'RSS'

**Comment by lislis** [comment]
oh and  Team blogs

**Comment by lislis** [comment]
And done.
Commit: 402f209f2e0efab9f3d51d71b97919289874639f
