### ISSUE TITLE
Illustrations for website

### ISSUE THREAD

**Issue by bioshrimp** [rails-girls-summer-of-code/summer-of-code-2014#9]
Hi guys :). 

great project by the way :D. 

@svenfuchs talked to me about how it would be nice to maybe include some illustrations for the website and so I looked thru some of my scribbles and made some new ones to post them here. Not super sure if it really fits ( it´s a bit naive), but here we go (and/or maybe others feel motivated to contribute something as well). 

[Link to pic 1](https://www.evernote.com/shard/s122/sh/53758919-b7c4-4403-a45e-862ca96cd3a1/61d5ebc3b72b7bdf8d5479df54bda1cb/deep/0/18.04.13%2020:03-Bildschirmkopie.png)
[Link to pic 2](https://www.evernote.com/shard/s122/sh/ae428fcc-6b18-4e49-aad7-c75a352606e1/210ca8df28573fbe8215c35129edb003/deep/0/18.04.13%2020:05-Bildschirmkopie.png)

And here download links to the illustrator/photoshop files in case someone would like to play around with it: 
https://dl.dropboxusercontent.com/u/14107562/soc1.ai (1,8 MB)
https://dl.dropboxusercontent.com/u/14107562/soc2.ai (785 KB)
https://dl.dropboxusercontent.com/u/14107562/soc3.ai (884 KB)
https://dl.dropboxusercontent.com/u/14107562/soc.psd (22,6 MB)

Have a nice evening. :)

**Comment by lindaliukas** [comment]
(just chiming in here, but love the illustrations!!)

## 

Linda Liukas
US +1 347 295 94 94
http://www.lindaliukas.fi

**Comment by svenfuchs** [comment]
i :heart: this stuff :)

@somamo @lislis what do you think?

**Comment by carlad** [comment]
yeah they're great :-)

**Comment by fannivuniconnu** [comment]
<3 those are wonderful. Great job!

---

**Comment by lislis** [comment]
Super nice! We definitely have to implement those!

**Comment by PragTob** [comment]
Totally awesome :-D

**Comment by carolinagc** [comment]
Really nice and cute illustrations <3

**Comment by jmentz** [comment]
Wow, absolutely great! We should totally add those into the website.

**Comment by somamo** [comment]
The illustrations are great. They will fit well into the page. I will
create a demo on Saturday to show, how we can embed them best.
Am 19.04.2013 11:03 schrieb "Johannes Mentz" notifications@github.com:

**Comment by bioshrimp** [comment]
Great :D. And let me know if you need anything in additional.

**Comment by somamo** [comment]
Thanks for the scribbles. I love them. We can use them all across the side. This is how they might look inside the page.  

![RG_summerofcode_home](https://f.cloud.github.com/assets/3679710/405401/0adbefa2-a9d6-11e2-9c34-f215a77f30b0.jpg)
![RG_summerofcode_FAQ](https://f.cloud.github.com/assets/3679710/405400/0a91ddf4-a9d6-11e2-9022-018eb186f916.jpg)

**Comment by thatbettina** [comment]
I love those robots. I want to hug them.
