### ISSUE TITLE
add link to http://www.ejaculesc.com/ to the footer

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#91]

**Comment by lislis** [comment]
Should I write something like 'Scribbles drawn by Ejaculesc' ?

**Comment by lislis** [comment]
Just saw it's aready been done :)
Commit: 0984d00a904220debb1dabf5818c536bd2baab82

**Comment by anikalindtner** [comment]
sorry, i forgot to close it. already done :)

**Comment by anikalindtner** [comment]
ahhahahaha! :D
