### ISSUE TITLE
add newsletter link to blog

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#93]
eepurl.com/BzMdL

or use this html, mailchimp suggests to have a build-in form:
https://gist.github.com/anikalindtner/f8929f70a515f247d28f

but you also can make it prettier :)

**Comment by lislis** [comment]
I would suggest an implementation with just one input field that expands on focus to show the other fields. If we put this in the sidebar of the blog I would also say we take out the donation button.

**Comment by anikalindtner** [comment]
yeah, that would be great!

**Comment by lislis** [comment]
@anikalindtner also newsletter for the blog. i can change to texts to whatever you like :)
d164278c21c0da1af471a809c065f6b48cf36b55

**Comment by anikalindtner** [comment]
thanks, i will think about that, but for now it's more than enough. wonderful. <3
