### ISSUE TITLE
FB: Add newletter box to sidebar

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code-2014#98]

**Comment by anikalindtner** [comment]
this is super urgent! can somebody implement this on the frontpage? here is the landing page: 
http://railsgirls.us7.list-manage.com/subscribe?u=36677d2ea7383a950d149c68b&id=243f532f22

**Comment by lislis** [comment]
@anikalindtner quick fix?
3b1d7efd246a43e529a4399124ff35ff4d05b07f

**Comment by anikalindtner** [comment]
awesome! thanks so much!
