### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code-2014#99]
Is currently the old Contact Page, just w/ a new name, see #66 

Please fill it with content or make some design suggestions

**Comment by svenfuchs** [comment]
Assigned @floord to this because @anikalindtner told me so :)

Also, if we are going to list all teams (like, organizers, supervisors, helpdesk etc.) here we should definitely do this dynamically and pull the data from the teams app. 

Should be easy to implement, I can help with that, too.

**Comment by FloorD** [comment]
Also, if we are going to list all teams (like, organizers, supervisors,
helpdesk etc.) here we should definitely do this dynamically and pull the
data from the teams app.

> definitely, will ask Andreas to help me out as well ;)

F

**Comment by svenfuchs** [comment]
:heart:

**Comment by FloorD** [comment]
![teampage](https://f.cloud.github.com/assets/1087213/1037496/b15bc89a-0f50-11e3-96f3-5ab674ec29f3.jpg)

Listing the Organizers team, Supervisors, Coaches, Mentors and Helpdesk with Twitter account and GitHub account. We're pulling the pictures from GitHub, so make sure you have one ;)

Planning to work on this together with @alicetragedy during the next vienna.rb (5/9)

(got the mockup in .psd too)

**Comment by anikalindtner** [comment]
hahaha! looks pretty good to me so far ;)))

no but seriously, can't wait to see this online ... awesome sauce! <3

**Comment by lislis** [comment]
comeback of the wavy border! +1

**Comment by FloorD** [comment]
I like waves.

**Comment by FloorD** [comment]
@alicetragedy helps me today, is there any way she can get commit rights or should it go through me? :)

**Comment by svenfuchs** [comment]
hey @FloorD I've added @alicetragedy to the collaborators team and she should have access now.

@alicetragedy welcome on board :)

:heart:

**Comment by FloorD** [comment]
Thanks, that's great!!

**Comment by alicetragedy** [comment]
hey @svenfuchs, hello! yes, everything worked perfectly, thank you. we'll be working on this in the next days I guess. cool. :heart:
